package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * AddrTyp generated by hbm2java
 */
@Entity
@Table(name = "addr_typ")
public class AddrTyp implements java.io.Serializable {

	private Integer id;
	private String addrTypDesc;
	@JsonIgnore
	private int addrTypF;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private String updId;
	@JsonIgnore
	private Date updTs;

	public AddrTyp() {
	}

	public AddrTyp(String addrTypDesc, byte addrTypF, Date crtTs) {
		this.addrTypDesc = addrTypDesc;
		this.addrTypF = addrTypF;
		this.crtTs = crtTs;
	}

	public AddrTyp(String addrTypDesc, byte addrTypF, String crtId, Date crtTs,
			String updId, Date updTs) {
		this.addrTypDesc = addrTypDesc;
		this.addrTypF = addrTypF;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "addr_typ_desc", nullable = false, length = 1000)
	public String getAddrTypDesc() {
		return this.addrTypDesc;
	}

	public void setAddrTypDesc(String addrTypDesc) {
		this.addrTypDesc = addrTypDesc;
	}

	@Column(name = "addr_typ_f", nullable = false)
	public int getAddrTypF() {
		return this.addrTypF;
	}

	public void setAddrTypF(int addrTypF) {
		this.addrTypF = addrTypF;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
