package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Advertisement generated by hbm2java
 */
@Entity
@Table(name = "advertisement", catalog = "spiceboxcoupon")
public class Advertisement implements java.io.Serializable {

	private Integer id;
	private String addUrl;

	public Advertisement() {
	}

	public Advertisement(String addUrl) {
		this.addUrl = addUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "add_url", nullable = false, length = 150)
	public String getAddUrl() {
		return this.addUrl;
	}

	public void setAddUrl(String addUrl) {
		this.addUrl = addUrl;
	}

}
