package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;


/**
 * Area generated by hbm2java
 */

@Entity
@Table(name = "area")
public class Area implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	@JsonIgnore
	private int cityId;
	@JsonIgnore
	private City city;
	private String areaDesc;
	@JsonIgnore
	private State state;
	@JsonIgnore
	private String lat;
	@JsonIgnore
	private String longt;
	
	private String addressDesc;
	
	//private Pincode pincode;
	@JsonIgnore
	private String pincode;
	@JsonIgnore
	private int areaF;
	@JsonIgnore
	private boolean dayF;
	@JsonIgnore
	private boolean nightF;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private String updId;
	@JsonIgnore
	private String updTs;
	
	@JsonIgnore
	private Set<Address> address = new HashSet<Address>(0);

	public Area() {
	}

	public Area(int cityId, String areaDesc, byte areaF, boolean dayF,
			boolean nightF, Date crtTs) {
		this.cityId = cityId;
		this.areaDesc = areaDesc;
		this.areaF = areaF;
		this.dayF = dayF;
		this.nightF = nightF;
		this.crtTs = crtTs;
	}

	public Area(int cityId, String areaDesc, String lat, String longt,
			byte areaF, boolean dayF, boolean nightF, String crtId, Date crtTs,
			String updId, String updTs) {
		this.cityId = cityId;
		this.areaDesc = areaDesc;
		this.lat = lat;
		this.longt = longt;
		this.areaF = areaF;
		this.dayF = dayF;
		this.nightF = nightF;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/*@Column(name = "city_id", nullable = false)
	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}*/

	@Column(name = "area_desc", nullable = false, length = 1000)
	public String getAreaDesc() {
		return this.areaDesc;
	}

	public void setAreaDesc(String areaDesc) {
		this.areaDesc = areaDesc;
	}

	@Column(name = "latitude", length = 500)
	public String getLat() {
		return this.lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	@Column(name = "longitude", length = 500)
	public String getLongt() {
		return longt;
	}

	public void setLongt(String longt) {
		this.longt = longt;
	}


	@Column(name = "area_f", nullable = false)
	public int getAreaF() {
		return this.areaF;
	}

	public void setAreaF(int areaF) {
		this.areaF = areaF;
	}

	@Column(name = "day_f", nullable = false)
	public boolean isDayF() {
		return this.dayF;
	}

	public void setDayF(boolean dayF) {
		this.dayF = dayF;
	}

	@Column(name = "night_f", nullable = false)
	public boolean isNightF() {
		return this.nightF;
	}

	public void setNightF(boolean nightF) {
		this.nightF = nightF;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	
	@Column(name = "upd_ts", length = 19)
	public String getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(String updTs) {
		this.updTs = updTs;
	}
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "city_id", nullable = false)
	public City getCity() {
		return city;
	}

	public void setCity(City city) {
		this.city = city;
	}
	@Column(name = "pincode", length = 45)
	public String getPincode() {
		return pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "state_id", nullable = false)
	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}
	@OneToMany(fetch=FetchType.LAZY,mappedBy="area")
	public Set<Address> getAddress() {
		return address;
	}

	public void setAddress(Set<Address> address) {
		this.address = address;
	}

	@Column(name = "address")
	public String getAddressDesc() {
		return addressDesc;
	}

	public void setAddressDesc(String addressDesc) {
		this.addressDesc = addressDesc;
	}
	
	/*@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "pincode", nullable = false)
	public Pincode getPincode() {
		return pincode;
	}

	public void setPincode(Pincode pincode) {
		this.pincode = pincode;
	}*/

	
}
