package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillHistory generated by hbm2java
 */
@Entity
@Table(name = "bill_history")
public class BillHistory implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int ordNo;
	private String billnumber;
	private int billdate;
	private String billComment;
	private String billdiscountComment;
	private String roundto;
	private String billAmount;
	private String foodbill;
	private String barbill;
	private String tax;
	private String schtax;
	private String foodvattax;
	private String barvattax;
	private String sertax;
	private String discount;
	private String liqDiscount;
	private String discountPercent;
	private String liqDiscountPercent;
	private String cash;
	private String card;
	private String coupon;
	private String returnAmt;
	private String date;
	private String time;
	private int reportStatus;
	private String crtId;
	private Date crtTs;
	private String updId;
	private String updTs;

	public BillHistory() {
	}

	public BillHistory(int ordNo, String billnumber, int billdate,
			String billComment, String billdiscountComment, String roundto,
			String billAmount, String foodbill, String barbill, String schtax,
			String foodvattax, String barvattax, String sertax,
			String liqDiscount, String discountPercent,
			String liqDiscountPercent, String returnAmt, String date,
			String time, int reportStatus, String crtId, Date crtTs) {
		this.ordNo = ordNo;
		this.billnumber = billnumber;
		this.billdate = billdate;
		this.billComment = billComment;
		this.billdiscountComment = billdiscountComment;
		this.roundto = roundto;
		this.billAmount = billAmount;
		this.foodbill = foodbill;
		this.barbill = barbill;
		this.schtax = schtax;
		this.foodvattax = foodvattax;
		this.barvattax = barvattax;
		this.sertax = sertax;
		this.liqDiscount = liqDiscount;
		this.discountPercent = discountPercent;
		this.liqDiscountPercent = liqDiscountPercent;
		this.returnAmt = returnAmt;
		this.date = date;
		this.time = time;
		this.reportStatus = reportStatus;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public BillHistory(int ordNo, String billnumber, int billdate,
			String billComment, String billdiscountComment, String roundto,
			String billAmount, String foodbill, String barbill, String tax,
			String schtax, String foodvattax, String barvattax, String sertax,
			String discount, String liqDiscount, String discountPercent,
			String liqDiscountPercent, String cash, String card, String coupon,
			String returnAmt, String date, String time, int reportStatus,
			String crtId, Date crtTs, String updId, String updTs) {
		this.ordNo = ordNo;
		this.billnumber = billnumber;
		this.billdate = billdate;
		this.billComment = billComment;
		this.billdiscountComment = billdiscountComment;
		this.roundto = roundto;
		this.billAmount = billAmount;
		this.foodbill = foodbill;
		this.barbill = barbill;
		this.tax = tax;
		this.schtax = schtax;
		this.foodvattax = foodvattax;
		this.barvattax = barvattax;
		this.sertax = sertax;
		this.discount = discount;
		this.liqDiscount = liqDiscount;
		this.discountPercent = discountPercent;
		this.liqDiscountPercent = liqDiscountPercent;
		this.cash = cash;
		this.card = card;
		this.coupon = coupon;
		this.returnAmt = returnAmt;
		this.date = date;
		this.time = time;
		this.reportStatus = reportStatus;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ord_no", nullable = false)
	public int getOrdNo() {
		return this.ordNo;
	}

	public void setOrdNo(int ordNo) {
		this.ordNo = ordNo;
	}

	@Column(name = "billnumber", nullable = false, length = 2000)
	public String getBillnumber() {
		return this.billnumber;
	}

	public void setBillnumber(String billnumber) {
		this.billnumber = billnumber;
	}

	@Column(name = "billdate", nullable = false)
	public int getBilldate() {
		return this.billdate;
	}

	public void setBilldate(int billdate) {
		this.billdate = billdate;
	}

	@Column(name = "bill_comment", nullable = false, length = 500)
	public String getBillComment() {
		return this.billComment;
	}

	public void setBillComment(String billComment) {
		this.billComment = billComment;
	}

	@Column(name = "billdiscount_comment", nullable = false, length = 500)
	public String getBilldiscountComment() {
		return this.billdiscountComment;
	}

	public void setBilldiscountComment(String billdiscountComment) {
		this.billdiscountComment = billdiscountComment;
	}

	@Column(name = "roundto", nullable = false, length = 500)
	public String getRoundto() {
		return this.roundto;
	}

	public void setRoundto(String roundto) {
		this.roundto = roundto;
	}

	@Column(name = "bill_amount", nullable = false, length = 500)
	public String getBillAmount() {
		return this.billAmount;
	}

	public void setBillAmount(String billAmount) {
		this.billAmount = billAmount;
	}

	@Column(name = "foodbill", nullable = false, length = 100)
	public String getFoodbill() {
		return this.foodbill;
	}

	public void setFoodbill(String foodbill) {
		this.foodbill = foodbill;
	}

	@Column(name = "barbill", nullable = false, length = 100)
	public String getBarbill() {
		return this.barbill;
	}

	public void setBarbill(String barbill) {
		this.barbill = barbill;
	}

	@Column(name = "tax", length = 100)
	public String getTax() {
		return this.tax;
	}

	public void setTax(String tax) {
		this.tax = tax;
	}

	@Column(name = "schtax", nullable = false, length = 100)
	public String getSchtax() {
		return this.schtax;
	}

	public void setSchtax(String schtax) {
		this.schtax = schtax;
	}

	@Column(name = "foodvattax", nullable = false, length = 100)
	public String getFoodvattax() {
		return this.foodvattax;
	}

	public void setFoodvattax(String foodvattax) {
		this.foodvattax = foodvattax;
	}

	@Column(name = "barvattax", nullable = false, length = 100)
	public String getBarvattax() {
		return this.barvattax;
	}

	public void setBarvattax(String barvattax) {
		this.barvattax = barvattax;
	}

	@Column(name = "sertax", nullable = false, length = 100)
	public String getSertax() {
		return this.sertax;
	}

	public void setSertax(String sertax) {
		this.sertax = sertax;
	}

	@Column(name = "discount", length = 200)
	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	@Column(name = "liq_discount", nullable = false, length = 200)
	public String getLiqDiscount() {
		return this.liqDiscount;
	}

	public void setLiqDiscount(String liqDiscount) {
		this.liqDiscount = liqDiscount;
	}

	@Column(name = "discount_percent", nullable = false, length = 100)
	public String getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(String discountPercent) {
		this.discountPercent = discountPercent;
	}

	@Column(name = "liq_discount_percent", nullable = false, length = 200)
	public String getLiqDiscountPercent() {
		return this.liqDiscountPercent;
	}

	public void setLiqDiscountPercent(String liqDiscountPercent) {
		this.liqDiscountPercent = liqDiscountPercent;
	}

	@Column(name = "cash", length = 45)
	public String getCash() {
		return this.cash;
	}

	public void setCash(String cash) {
		this.cash = cash;
	}

	@Column(name = "card", length = 45)
	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	@Column(name = "coupon", length = 45)
	public String getCoupon() {
		return this.coupon;
	}

	public void setCoupon(String coupon) {
		this.coupon = coupon;
	}

	@Column(name = "return_amt", nullable = false, length = 500)
	public String getReturnAmt() {
		return this.returnAmt;
	}

	public void setReturnAmt(String returnAmt) {
		this.returnAmt = returnAmt;
	}

	@Column(name = "date", nullable = false, length = 100)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "time", nullable = false, length = 200)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "report_status", nullable = false)
	public int getReportStatus() {
		return this.reportStatus;
	}

	public void setReportStatus(int reportStatus) {
		this.reportStatus = reportStatus;
	}

	@Column(name = "crt_id", nullable = false, length = 500)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 500)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "upd_ts", length = 500)
	public String getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(String updTs) {
		this.updTs = updTs;
	}

}
