package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bills generated by hbm2java
 */
@Entity
@Table(name = "bills", catalog = "spiceboxcoupon")
public class Bills implements java.io.Serializable {

	private Integer id;
	private String bilNo;
	private int ordNo;
	private int tblCode;
	private String gstCntcNo;
	private String foodBillAmnt;
	private Integer taxCode;
	private Integer disCode;
	private String totBillAmnt;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public Bills() {
	}

	public Bills(String bilNo, int ordNo, int tblCode, String foodBillAmnt,
			String totBillAmnt, Date crtTs, String crtId, String updId) {
		this.bilNo = bilNo;
		this.ordNo = ordNo;
		this.tblCode = tblCode;
		this.foodBillAmnt = foodBillAmnt;
		this.totBillAmnt = totBillAmnt;
		this.crtTs = crtTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	public Bills(String bilNo, int ordNo, int tblCode, String gstCntcNo,
			String foodBillAmnt, Integer taxCode, Integer disCode,
			String totBillAmnt, Date crtTs, Date updTs, String crtId,
			String updId) {
		this.bilNo = bilNo;
		this.ordNo = ordNo;
		this.tblCode = tblCode;
		this.gstCntcNo = gstCntcNo;
		this.foodBillAmnt = foodBillAmnt;
		this.taxCode = taxCode;
		this.disCode = disCode;
		this.totBillAmnt = totBillAmnt;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "bil_no", nullable = false, length = 65535)
	public String getBilNo() {
		return this.bilNo;
	}

	public void setBilNo(String bilNo) {
		this.bilNo = bilNo;
	}

	@Column(name = "ord_no", nullable = false)
	public int getOrdNo() {
		return this.ordNo;
	}

	public void setOrdNo(int ordNo) {
		this.ordNo = ordNo;
	}

	@Column(name = "tbl_code", nullable = false)
	public int getTblCode() {
		return this.tblCode;
	}

	public void setTblCode(int tblCode) {
		this.tblCode = tblCode;
	}

	@Column(name = "gst_cntc_no", length = 65535)
	public String getGstCntcNo() {
		return this.gstCntcNo;
	}

	public void setGstCntcNo(String gstCntcNo) {
		this.gstCntcNo = gstCntcNo;
	}

	@Column(name = "food_bill_amnt", nullable = false, length = 65535)
	public String getFoodBillAmnt() {
		return this.foodBillAmnt;
	}

	public void setFoodBillAmnt(String foodBillAmnt) {
		this.foodBillAmnt = foodBillAmnt;
	}

	@Column(name = "tax_code")
	public Integer getTaxCode() {
		return this.taxCode;
	}

	public void setTaxCode(Integer taxCode) {
		this.taxCode = taxCode;
	}

	@Column(name = "dis_code")
	public Integer getDisCode() {
		return this.disCode;
	}

	public void setDisCode(Integer disCode) {
		this.disCode = disCode;
	}

	@Column(name = "tot_bill_amnt", nullable = false, length = 65535)
	public String getTotBillAmnt() {
		return this.totBillAmnt;
	}

	public void setTotBillAmnt(String totBillAmnt) {
		this.totBillAmnt = totBillAmnt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", nullable = false)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
