package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustMealCupnRelt generated by hbm2java
 */
@Entity
@Table(name = "cust_meal_cupn_relt")
public class CancelledOrderDetails implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String cupnDesc;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;
	private Integer custDetId;
	private float cupnAmnt;
	private String custBillHistId;
	private Integer cupnF;
	private String custOrdDetId;

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cupn_desc", length = 100)
	public String getCupnDesc() {
		return this.cupnDesc;
	}

	public void setCupnDesc(String cupnDesc) {
		this.cupnDesc = cupnDesc;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "cust_det_id")
	public Integer getCustDetId() {
		return this.custDetId;
	}

	public void setCustDetId(Integer custDetId) {
		this.custDetId = custDetId;
	}

	@Column(name = "cupn_amnt")
	public float getCupnAmnt() {
		return this.cupnAmnt;
	}

	public void setCupnAmnt(float cupnAmnt) {
		this.cupnAmnt = cupnAmnt;
	}

	@Column(name = "cust_bill_hist_id", length = 45)
	public String getCustBillHistId() {
		return this.custBillHistId;
	}

	public void setCustBillHistId(String custBillHistId) {
		this.custBillHistId = custBillHistId;
	}

	@Column(name = "cupn_f")
	public Integer getCupnF() {
		return this.cupnF;
	}

	public void setCupnF(Integer cupnF) {
		this.cupnF = cupnF;
	}

	@Column(name = "cust_ord_det_id", length = 45)
	public String getCustOrdDetId() {
		return this.custOrdDetId;
	}

	public void setCustOrdDetId(String custOrdDetId) {
		this.custOrdDetId = custOrdDetId;
	}

}
