package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChfSpl generated by hbm2java
 */
@Entity
@Table(name = "chf_spl", catalog = "starfoodlocal")
public class ChfSpl implements java.io.Serializable {

	private Integer id;
	private int chfSplCode;
	private String chfSplDesc;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public ChfSpl() {
	}

	public ChfSpl(int chfSplCode, String chfSplDesc, Date crtTs, Date updTs,
			String crtId) {
		this.chfSplCode = chfSplCode;
		this.chfSplDesc = chfSplDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
	}

	public ChfSpl(int chfSplCode, String chfSplDesc, Date crtTs, Date updTs,
			String crtId, String updId) {
		this.chfSplCode = chfSplCode;
		this.chfSplDesc = chfSplDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "chf_spl_code", nullable = false)
	public int getChfSplCode() {
		return this.chfSplCode;
	}

	public void setChfSplCode(int chfSplCode) {
		this.chfSplCode = chfSplCode;
	}

	@Column(name = "chf_spl_desc", nullable = false, length = 65535)
	public String getChfSplDesc() {
		return this.chfSplDesc;
	}

	public void setChfSplDesc(String chfSplDesc) {
		this.chfSplDesc = chfSplDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
