package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComboOrdDet generated by hbm2java
 */
@Entity
@Table(name = "combo_ord_det", catalog = "spiceboxcoupon")
public class ComboOrdDet implements java.io.Serializable {

	private Integer id;
	private String kotNo;
	private Integer tblNo;
	private Integer ordNo;
	private Integer foodCatgCode;
	private Integer catgSect;
	private int kotCatg;
	private int foodItmCode;
	private int foodItmQty;
	private String date;
	private int billdate;
	private Integer foodItmStCode;
	private Date crtTs;
	private Date upsTs;
	private String crtId;
	private String updId;

	public ComboOrdDet() {
	}

	public ComboOrdDet(String kotNo, int kotCatg, int foodItmCode,
			int foodItmQty, String date, int billdate, Date crtTs, String crtId) {
		this.kotNo = kotNo;
		this.kotCatg = kotCatg;
		this.foodItmCode = foodItmCode;
		this.foodItmQty = foodItmQty;
		this.date = date;
		this.billdate = billdate;
		this.crtTs = crtTs;
		this.crtId = crtId;
	}

	public ComboOrdDet(String kotNo, Integer tblNo, Integer ordNo,
			Integer foodCatgCode, Integer catgSect, int kotCatg,
			int foodItmCode, int foodItmQty, String date, int billdate,
			Integer foodItmStCode, Date crtTs, Date upsTs, String crtId,
			String updId) {
		this.kotNo = kotNo;
		this.tblNo = tblNo;
		this.ordNo = ordNo;
		this.foodCatgCode = foodCatgCode;
		this.catgSect = catgSect;
		this.kotCatg = kotCatg;
		this.foodItmCode = foodItmCode;
		this.foodItmQty = foodItmQty;
		this.date = date;
		this.billdate = billdate;
		this.foodItmStCode = foodItmStCode;
		this.crtTs = crtTs;
		this.upsTs = upsTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "kot_no", nullable = false, length = 200)
	public String getKotNo() {
		return this.kotNo;
	}

	public void setKotNo(String kotNo) {
		this.kotNo = kotNo;
	}

	@Column(name = "tbl_no")
	public Integer getTblNo() {
		return this.tblNo;
	}

	public void setTblNo(Integer tblNo) {
		this.tblNo = tblNo;
	}

	@Column(name = "ord_no")
	public Integer getOrdNo() {
		return this.ordNo;
	}

	public void setOrdNo(Integer ordNo) {
		this.ordNo = ordNo;
	}

	@Column(name = "food_catg_code")
	public Integer getFoodCatgCode() {
		return this.foodCatgCode;
	}

	public void setFoodCatgCode(Integer foodCatgCode) {
		this.foodCatgCode = foodCatgCode;
	}

	@Column(name = "catg_sect")
	public Integer getCatgSect() {
		return this.catgSect;
	}

	public void setCatgSect(Integer catgSect) {
		this.catgSect = catgSect;
	}

	@Column(name = "kot_catg", nullable = false)
	public int getKotCatg() {
		return this.kotCatg;
	}

	public void setKotCatg(int kotCatg) {
		this.kotCatg = kotCatg;
	}

	@Column(name = "food_itm_code", nullable = false)
	public int getFoodItmCode() {
		return this.foodItmCode;
	}

	public void setFoodItmCode(int foodItmCode) {
		this.foodItmCode = foodItmCode;
	}

	@Column(name = "food_itm_qty", nullable = false)
	public int getFoodItmQty() {
		return this.foodItmQty;
	}

	public void setFoodItmQty(int foodItmQty) {
		this.foodItmQty = foodItmQty;
	}

	@Column(name = "date", nullable = false, length = 100)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "billdate", nullable = false)
	public int getBilldate() {
		return this.billdate;
	}

	public void setBilldate(int billdate) {
		this.billdate = billdate;
	}

	@Column(name = "food_itm_st_code")
	public Integer getFoodItmStCode() {
		return this.foodItmStCode;
	}

	public void setFoodItmStCode(Integer foodItmStCode) {
		this.foodItmStCode = foodItmStCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ups_ts", length = 19)
	public Date getUpsTs() {
		return this.upsTs;
	}

	public void setUpsTs(Date upsTs) {
		this.upsTs = upsTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
