package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CombOfr generated by hbm2java
 */
@Entity
@Table(name = "comb_ofr", catalog = "spiceboxcoupon")
public class CombOfr implements java.io.Serializable {

	private Integer id;
	private int combOfrCode;
	private String combOfrDesc;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public CombOfr() {
	}

	public CombOfr(int combOfrCode, String combOfrDesc, Date crtTs, Date updTs) {
		this.combOfrCode = combOfrCode;
		this.combOfrDesc = combOfrDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public CombOfr(int combOfrCode, String combOfrDesc, Date crtTs, Date updTs,
			String crtId, String updId) {
		this.combOfrCode = combOfrCode;
		this.combOfrDesc = combOfrDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "comb_ofr_code", nullable = false)
	public int getCombOfrCode() {
		return this.combOfrCode;
	}

	public void setCombOfrCode(int combOfrCode) {
		this.combOfrCode = combOfrCode;
	}

	@Column(name = "comb_ofr_desc", nullable = false, length = 65535)
	public String getCombOfrDesc() {
		return this.combOfrDesc;
	}

	public void setCombOfrDesc(String combOfrDesc) {
		this.combOfrDesc = combOfrDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
