package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Crncy generated by hbm2java
 */
@Entity
@Table(name = "crncy", catalog = "starfoodlocal")
public class Crncy implements java.io.Serializable {

	private Integer id;
	private int curCode;
	private String curDesc;
	private String curSbl;
	private boolean curVisF;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;
	private String curUniCode;

	public Crncy() {
	}

	public Crncy(int curCode, String curDesc, String curSbl, boolean curVisF,
			Date crtTs, Date updTs, String crtId, String curUniCode) {
		this.curCode = curCode;
		this.curDesc = curDesc;
		this.curSbl = curSbl;
		this.curVisF = curVisF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.curUniCode = curUniCode;
	}

	public Crncy(int curCode, String curDesc, String curSbl, boolean curVisF,
			Date crtTs, Date updTs, String crtId, String updId,
			String curUniCode) {
		this.curCode = curCode;
		this.curDesc = curDesc;
		this.curSbl = curSbl;
		this.curVisF = curVisF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
		this.curUniCode = curUniCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cur_code", nullable = false)
	public int getCurCode() {
		return this.curCode;
	}

	public void setCurCode(int curCode) {
		this.curCode = curCode;
	}

	@Column(name = "cur_desc", nullable = false, length = 65535)
	public String getCurDesc() {
		return this.curDesc;
	}

	public void setCurDesc(String curDesc) {
		this.curDesc = curDesc;
	}

	@Column(name = "cur_sbl", nullable = false, length = 100)
	public String getCurSbl() {
		return this.curSbl;
	}

	public void setCurSbl(String curSbl) {
		this.curSbl = curSbl;
	}

	@Column(name = "cur_vis_f", nullable = false)
	public boolean isCurVisF() {
		return this.curVisF;
	}

	public void setCurVisF(boolean curVisF) {
		this.curVisF = curVisF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "cur_uni_code", nullable = false, length = 45)
	public String getCurUniCode() {
		return this.curUniCode;
	}

	public void setCurUniCode(String curUniCode) {
		this.curUniCode = curUniCode;
	}

}
