package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CupnCatg generated by hbm2java
 */
@Entity
@Table(name = "cupn_catg", catalog = "starfoodlocal")
public class CupnCatg implements java.io.Serializable {

	private Integer id;
	private String cupnCatgDesc;
	private String cupnCatgF;
	private String crtTs;
	private String crtId;
	private String updId;
	private String updTs;

	public CupnCatg() {
	}

	public CupnCatg(String cupnCatgDesc, String cupnCatgF, String crtTs,
			String crtId, String updId, String updTs) {
		this.cupnCatgDesc = cupnCatgDesc;
		this.cupnCatgF = cupnCatgF;
		this.crtTs = crtTs;
		this.crtId = crtId;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cupn_catg_desc", length = 45)
	public String getCupnCatgDesc() {
		return this.cupnCatgDesc;
	}

	public void setCupnCatgDesc(String cupnCatgDesc) {
		this.cupnCatgDesc = cupnCatgDesc;
	}

	@Column(name = "cupn_catg_f", length = 45)
	public String getCupnCatgF() {
		return this.cupnCatgF;
	}

	public void setCupnCatgF(String cupnCatgF) {
		this.cupnCatgF = cupnCatgF;
	}

	@Column(name = "crt_ts", length = 45)
	public String getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(String crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "upd_ts", length = 45)
	public String getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(String updTs) {
		this.updTs = updTs;
	}

}
