package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CupnTyp generated by hbm2java
 */
@Entity
@Table(name = "cupn_typ", catalog = "starfoodlocal")
public class CupnTyp implements java.io.Serializable {

	private Integer id;
	private String cupnTypDesc;
	private Date crtTs;
	private String crtId;
	private String updTs;
	private String updId;
	private Integer cupnTypF;

	public CupnTyp() {
	}

	public CupnTyp(String cupnTypDesc, Date crtTs, String crtId, String updTs,
			String updId, Integer cupnTypF) {
		this.cupnTypDesc = cupnTypDesc;
		this.crtTs = crtTs;
		this.crtId = crtId;
		this.updTs = updTs;
		this.updId = updId;
		this.cupnTypF = cupnTypF;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cupn_typ_desc", length = 45)
	public String getCupnTypDesc() {
		return this.cupnTypDesc;
	}

	public void setCupnTypDesc(String cupnTypDesc) {
		this.cupnTypDesc = cupnTypDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_ts", length = 45)
	public String getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(String updTs) {
		this.updTs = updTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "cupn_typ_f")
	public Integer getCupnTypF() {
		return this.cupnTypF;
	}

	public void setCupnTypF(Integer cupnTypF) {
		this.cupnTypF = cupnTypF;
	}

}
