package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CupnDet generated by hbm2java
 */
@Entity
@Table(name = "cupn_det")
public class CupnDet implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private int cupnId;
	private int custDetId;
	private int custBillHistId;
	private String cupnAmount;
	private int cupnAmontF;
	private String crtTs;
	private String crtId;
	private String updId;
	private String updTs;

	public CupnDet() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cupn_id", length = 45)
	public int getCupnId() {
		return this.cupnId;
	}

	public void setCupnId(int cupnId) {
		this.cupnId = cupnId;
	}

	@Column(name = "cust_det_id", length = 45)
	public int getCustDetId() {
		return this.custDetId;
	}

	public void setCustDetId(int custDetId) {
		this.custDetId = custDetId;
	}

	@Column(name = "cust_bill_hist_id", length = 45)
	public int getCustBillHistId() {
		return this.custBillHistId;
	}

	public void setCustBillHistId(int custBillHistId) {
		this.custBillHistId = custBillHistId;
	}

	@Column(name = "cupn_amount", length = 45)
	public String getCupnAmount() {
		return this.cupnAmount;
	}

	public void setCupnAmount(String cupnAmount) {
		this.cupnAmount = cupnAmount;
	}

	@Column(name = "cupn_amont_f", length = 45)
	public int getCupnAmontF() {
		return this.cupnAmontF;
	}

	public void setCupnAmontF(int cupnAmontF) {
		this.cupnAmontF = cupnAmontF;
	}

	@Column(name = "crt_ts", length = 45)
	public String getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(String crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "upd_ts", length = 45)
	public String getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(String updTs) {
		this.updTs = updTs;
	}

}
