package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cus generated by hbm2java
 */
@Entity
@Table(name = "cus", catalog = "starfoodlocal")
public class Cus implements java.io.Serializable {

	private Integer id;
	private Integer cusCode;
	private String cusDesc;
	private int cusSrlNo;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;
	private String cusVisF;

	public Cus() {
	}

	public Cus(String cusDesc, int cusSrlNo, Date crtTs, String crtId,
			String cusVisF) {
		this.cusDesc = cusDesc;
		this.cusSrlNo = cusSrlNo;
		this.crtTs = crtTs;
		this.crtId = crtId;
		this.cusVisF = cusVisF;
	}

	public Cus(Integer cusCode, String cusDesc, int cusSrlNo, Date crtTs,
			Date updTs, String crtId, String updId, String cusVisF) {
		this.cusCode = cusCode;
		this.cusDesc = cusDesc;
		this.cusSrlNo = cusSrlNo;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
		this.cusVisF = cusVisF;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cus_code")
	public Integer getCusCode() {
		return this.cusCode;
	}

	public void setCusCode(Integer cusCode) {
		this.cusCode = cusCode;
	}

	@Column(name = "cus_desc", nullable = false)
	public String getCusDesc() {
		return this.cusDesc;
	}

	public void setCusDesc(String cusDesc) {
		this.cusDesc = cusDesc;
	}

	@Column(name = "cus_srl_no", nullable = false)
	public int getCusSrlNo() {
		return this.cusSrlNo;
	}

	public void setCusSrlNo(int cusSrlNo) {
		this.cusSrlNo = cusSrlNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "cus_vis_f", nullable = false, length = 45)
	public String getCusVisF() {
		return this.cusVisF;
	}

	public void setCusVisF(String cusVisF) {
		this.cusVisF = cusVisF;
	}

}
