package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustRefrlRelt generated by hbm2java
 */
@Entity
@Table(name = "cust_refrl_relt")
public class CustRefrlRelt implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String refrlDesc;
	private int refrlTypId;
	private int custDetId;
	private String invtGustEmailId;
	private String invtGustCntnNo;
	private int cupnId;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public CustRefrlRelt() {
	}

	public CustRefrlRelt(String refrlDesc, int refrlTypId, int custDetId,
			String invtGustEmailId, String invtGustCntnNo, int cupnId,
			String crtId, Date crtTs) {
		this.refrlDesc = refrlDesc;
		this.refrlTypId = refrlTypId;
		this.custDetId = custDetId;
		this.invtGustEmailId = invtGustEmailId;
		this.invtGustCntnNo = invtGustCntnNo;
		this.cupnId = cupnId;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public CustRefrlRelt(String refrlDesc, int refrlTypId, int custDetId,
			String invtGustEmailId, String invtGustCntnNo, int cupnId,
			String crtId, Date crtTs, String updId, Date updTs) {
		this.refrlDesc = refrlDesc;
		this.refrlTypId = refrlTypId;
		this.custDetId = custDetId;
		this.invtGustEmailId = invtGustEmailId;
		this.invtGustCntnNo = invtGustCntnNo;
		this.cupnId = cupnId;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "refrl_desc", nullable = false, length = 200)
	public String getRefrlDesc() {
		return this.refrlDesc;
	}

	public void setRefrlDesc(String refrlDesc) {
		this.refrlDesc = refrlDesc;
	}

	@Column(name = "refrl_typ_id", nullable = false)
	public int getRefrlTypId() {
		return this.refrlTypId;
	}

	public void setRefrlTypId(int refrlTypId) {
		this.refrlTypId = refrlTypId;
	}

	@Column(name = "cust_det_id", nullable = false)
	public int getCustDetId() {
		return this.custDetId;
	}

	public void setCustDetId(int custDetId) {
		this.custDetId = custDetId;
	}

	@Column(name = "invt_gust_email_id", nullable = false, length = 200)
	public String getInvtGustEmailId() {
		return this.invtGustEmailId;
	}

	public void setInvtGustEmailId(String invtGustEmailId) {
		this.invtGustEmailId = invtGustEmailId;
	}

	@Column(name = "invt_gust_cntn_no", nullable = false, length = 100)
	public String getInvtGustCntnNo() {
		return this.invtGustCntnNo;
	}

	public void setInvtGustCntnNo(String invtGustCntnNo) {
		this.invtGustCntnNo = invtGustCntnNo;
	}

	@Column(name = "cupn_id", nullable = false)
	public int getCupnId() {
		return this.cupnId;
	}

	public void setCupnId(int cupnId) {
		this.cupnId = cupnId;
	}

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
