package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustOrdShare generated by hbm2java
 */
@Entity
@Table(name = "cust_ord_share")
public class CustOrdShare implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int custOrdDetId;
	private Integer cancelQty;
	private String shareForDate;
	private Integer cpnRefId;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public CustOrdShare() {
	}

	public CustOrdShare(int custOrdDetId, String shareForDate, Date crtTs,
			String crtId) {
		this.custOrdDetId = custOrdDetId;
		this.shareForDate = shareForDate;
		this.crtTs = crtTs;
		this.crtId = crtId;
	}

	public CustOrdShare(int custOrdDetId, Integer cancelQty,
			String shareForDate, Integer cpnRefId, Date crtTs, Date updTs,
			String crtId, String updId) {
		this.custOrdDetId = custOrdDetId;
		this.cancelQty = cancelQty;
		this.shareForDate = shareForDate;
		this.cpnRefId = cpnRefId;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cust_ord_det_id", nullable = false)
	public int getCustOrdDetId() {
		return this.custOrdDetId;
	}

	public void setCustOrdDetId(int custOrdDetId) {
		this.custOrdDetId = custOrdDetId;
	}

	@Column(name = "cancel_qty")
	public Integer getCancelQty() {
		return this.cancelQty;
	}

	public void setCancelQty(Integer cancelQty) {
		this.cancelQty = cancelQty;
	}

	@Column(name = "share_for_date", nullable = false, length = 100)
	public String getShareForDate() {
		return this.shareForDate;
	}

	public void setShareForDate(String shareForDate) {
		this.shareForDate = shareForDate;
	}

	@Column(name = "cpn_ref_id")
	public Integer getCpnRefId() {
		return this.cpnRefId;
	}

	public void setCpnRefId(Integer cpnRefId) {
		this.cpnRefId = cpnRefId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
