package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustBillHist generated by hbm2java
 */
@Entity
@Table(name = "cust_bill_hist")
public class CustBillHist implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private int id;
	private int custDetId;
	private Float subAmnt;
	private Float taxAmnt;
	private Float delChrg;
	private Float grndTot;
	private Float vatTax;
	private Float schTax;
	private Float serTax;
	private Float gstTax;
	private Float cupnDiscAmnt;
	private Float redeemCancelAmnt;
	private int paymentGatewayTypId;
	private String transactionId;
	private int payModId;
	private Float subGrndTot;
	private int ordrStId;
	private String ordStDt;
	private String ordEndDt;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cust_det_id")
	public int getCustDetId() {
		return this.custDetId;
	}

	public void setCustDetId(int custDetId) {
		this.custDetId = custDetId;
	}

	@Column(name = "sub_amnt", precision = 20)
	public Float getSubAmnt() {
		return this.subAmnt;
	}

	public void setSubAmnt(Float subAmnt) {
		this.subAmnt = subAmnt;
	}

	@Column(name = "tax_amnt", precision = 20)
	public Float getTaxAmnt() {
		return this.taxAmnt;
	}

	public void setTaxAmnt(Float taxAmnt) {
		this.taxAmnt = taxAmnt;
	}

	@Column(name = "del_chrg", precision = 20)
	public Float getDelChrg() {
		return this.delChrg;
	}

	public void setDelChrg(Float delChrg) {
		this.delChrg = delChrg;
	}

	@Column(name = "grnd_tot", precision = 20)
	public Float getGrndTot() {
		return this.grndTot;
	}

	public void setGrndTot(Float grndTot) {
		this.grndTot = grndTot;
	}

	@Column(name = "vat_tax",  precision = 20)
	public Float getVatTax() {
		return this.vatTax;
	}

	public void setVatTax(Float vatTax) {
		this.vatTax = vatTax;
	}

	@Column(name = "sch_tax",  precision = 20)
	public Float getSchTax() {
		return this.schTax;
	}

	public void setSchTax(Float schTax) {
		this.schTax = schTax;
	}

	@Column(name = "ser_tax", precision = 20)
	public Float getSerTax() {
		return this.serTax;
	}

	public void setSerTax(Float serTax) {
		this.serTax = serTax;
	}

	@Column(name = "gst_tax", precision = 20)
	public Float getGstTax() {
		return this.gstTax;
	}

	public void setGstTax(Float gstTax) {
		this.gstTax = gstTax;
	}

	@Column(name = "cupn_disc_amnt")
	public Float getCupnDiscAmnt() {
		return this.cupnDiscAmnt;
	}

	public void setCupnDiscAmnt(Float cupnDiscAmnt) {
		this.cupnDiscAmnt = cupnDiscAmnt;
	}

	@Column(name = "redeem_cancel_amnt")
	public Float getRedeemCancelAmnt() {
		return this.redeemCancelAmnt;
	}

	public void setRedeemCancelAmnt(Float redeemCancelAmnt) {
		this.redeemCancelAmnt = redeemCancelAmnt;
	}

	@Column(name = "payment_gateway_typ_id")
	public int getPaymentGatewayTypId() {
		return this.paymentGatewayTypId;
	}

	public void setPaymentGatewayTypId(int paymentGatewayTypId) {
		this.paymentGatewayTypId = paymentGatewayTypId;
	}

	@Column(name = "transaction_id", length = 500)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "pay_mod_id", length = 100)
	public int getPayModId() {
		return this.payModId;
	}

	public void setPayModId(int payModId) {
		this.payModId = payModId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", nullable = false, length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "sub_grnd_tot")
	public Float getSubGrndTot() {
		return subGrndTot;
	}

	public void setSubGrndTot(Float subGrndTot) {
		this.subGrndTot = subGrndTot;
	}
	
	@Column(name = "ordr_st_id", nullable = false)
	public int getOrdrStId() {
		return this.ordrStId;
	}

	public void setOrdrStId(int ordrStId) {
		this.ordrStId = ordrStId;
	}
	
	@Column(name = "ord_st_dt", length = 200)
	public String getOrdStDt() {
		return this.ordStDt;
	}

	public void setOrdStDt(String ordStDt) {
		this.ordStDt = ordStDt;
	}

	@Column(name = "ord_end_dt", length = 200)
	public String getOrdEndDt() {
		return this.ordEndDt;
	}

	public void setOrdEndDt(String ordEndDt) {
		this.ordEndDt = ordEndDt;
	}


}
