package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;


/**
 * CustCupnRelt generated by hbm2java
 */
@Entity
@Table(name = "cust_cupn_relt")
public class CustCupnRelt implements java.io.Serializable {
	 private static final long serialVersionUID = 1L;
	private Integer id;
	private Cupn cupn;
	private String cupnCode;
	 @JsonIgnore
	private String crtId;
	 @JsonIgnore
	private Date crtTs;
	 @JsonIgnore
	private String updId;
	 @JsonIgnore
	private Date updTs;
	private int custDetId;
	

	public CustCupnRelt() {
	}

	public CustCupnRelt(String crtId, Date crtTs, int custDetId) {
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.custDetId = custDetId;
		
	}

	public CustCupnRelt(String cupnCode, String crtId, Date crtTs,
			String updId, Date updTs, int custDetId) {
		this.cupnCode = cupnCode;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
		this.custDetId = custDetId;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cupn_code", length = 100)
	public String getCupnCode() {
		return this.cupnCode;
	}

	public void setCupnCode(String cupnCode) {
		this.cupnCode = cupnCode;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "cust_det_id", nullable = false)
	public int getCustDetId() {
		return this.custDetId;
	}

	public void setCustDetId(int custDetId) {
		this.custDetId = custDetId;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cupn_id", nullable = false)
	public Cupn getCupn() {
		return cupn;
	}

	public void setCupn(Cupn cupn) {
		this.cupn = cupn;
	}

	

}
