package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustOrdrs generated by hbm2java
 */
@Entity
@Table(name = "cust_ordrs")
public class CustOrdrs implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int custBillId;
	private int ordNo;
	private float subTotal;
	private float totalTax;
	private float grandTotal;
	private float vatTax;
	private float schTax;
	private float serTax;
	private float gstTax;
	private float cupnDiscAmnt;
	private float redeemCancelAmnt;
	private int custDetId;
	//private Date ordStDate;
	//private Date ordEndDate;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;
	private Date ordDt;
	private int ordrStId;
	private int mealTimeId;
	private float pkgsSumAmount;


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cust_bill_id", nullable = false)
	public int getCustBillId() {
		return this.custBillId;
	}

	public void setCustBillId(int custBillId) {
		this.custBillId = custBillId;
	}

	@Column(name = "ord_no", nullable = false)
	public int getOrdNo() {
		return this.ordNo;
	}

	public void setOrdNo(int ordNo) {
		this.ordNo = ordNo;
	}

	@Column(name = "sub_total", nullable = false, precision = 20)
	public float getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(float subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "total_tax", nullable = false, precision = 20)
	public float getTotalTax() {
		return this.totalTax;
	}

	public void setTotalTax(float totalTax) {
		this.totalTax = totalTax;
	}

	@Column(name = "grand_total", nullable = false, precision = 20)
	public float getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(float grandTotal) {
		this.grandTotal = grandTotal;
	}

	@Column(name = "vat_tax", nullable = false, precision = 20)
	public float getVatTax() {
		return this.vatTax;
	}

	public void setVatTax(float vatTax) {
		this.vatTax = vatTax;
	}

	@Column(name = "sch_tax", nullable = false, precision = 20)
	public float getSchTax() {
		return this.schTax;
	}

	public void setSchTax(float schTax) {
		this.schTax = schTax;
	}

	@Column(name = "ser_tax", nullable = false, precision = 20)
	public float getSerTax() {
		return this.serTax;
	}

	public void setSerTax(float serTax) {
		this.serTax = serTax;
	}

	@Column(name = "gst_tax", nullable = false, precision = 20)
	public float getGstTax() {
		return this.gstTax;
	}

	public void setGstTax(float gstTax) {
		this.gstTax = gstTax;
	}

	@Column(name = "cupn_disc_amnt", nullable = false, precision = 20)
	public float getCupnDiscAmnt() {
		return this.cupnDiscAmnt;
	}

	public void setCupnDiscAmnt(float cupnDiscAmnt) {
		this.cupnDiscAmnt = cupnDiscAmnt;
	}

	@Column(name = "redeem_cancel_amnt", nullable = false, precision = 20)
	public float getRedeemCancelAmnt() {
		return this.redeemCancelAmnt;
	}

	public void setRedeemCancelAmnt(float redeemCancelAmnt) {
		this.redeemCancelAmnt = redeemCancelAmnt;
	}

	@Column(name = "cust_det_id", nullable = false)
	public int getCustDetId() {
		return this.custDetId;
	}

	public void setCustDetId(int custDetId) {
		this.custDetId = custDetId;
	}

/*	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ord_st_date", nullable = false, length = 19)
	public Date getOrdStDate() {
		return this.ordStDate;
	}

	public void setOrdStDate(Date ordStDate) {
		this.ordStDate = ordStDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ord_end_date", nullable = false, length = 19)
	public Date getOrdEndDate() {
		return this.ordEndDate;
	}

	public void setOrdEndDate(Date ordEndDate) {
		this.ordEndDate = ordEndDate;
	}*/

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", nullable = false, length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ord_dt", length = 19)
	public Date getOrdDt() {
		return this.ordDt;
	}

	public void setOrdDt(Date ordDt) {
		this.ordDt = ordDt;
	}

	@Column(name = "ordr_st_id", nullable = false)
	public int getOrdrStId() {
		return this.ordrStId;
	}

	public void setOrdrStId(int ordrStId) {
		this.ordrStId = ordrStId;
	}
	
	@Column(name = "meal_time_id")
	public Integer getMealTimeId() {
		return this.mealTimeId;
	}

	public void setMealTimeId(Integer mealTimeId) {
		this.mealTimeId = mealTimeId;
	}

	@Column(name = "pkgs_sum_amount")
	public float getPkgsSumAmount() {
		return pkgsSumAmount;
	}

	public void setPkgsSumAmount(float pkgsSumAmount) {
		this.pkgsSumAmount = pkgsSumAmount;
	}
	
	
}
