package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustFdbkRelt generated by hbm2java
 */
@Entity
@Table(name = "cust_fdbk_relt")
public class CustFdbkRelt implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int custDetId;
	private int fdbkQuesId;
	private String fdbkQuesResp;
	private String fdbkCmnts;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public CustFdbkRelt() {
	}

	public CustFdbkRelt(int custDetId, int fdbkQuesId, String fdbkQuesResp,
			String fdbkCmnts, String crtId, Date crtTs) {
		this.custDetId = custDetId;
		this.fdbkQuesId = fdbkQuesId;
		this.fdbkQuesResp = fdbkQuesResp;
		this.fdbkCmnts = fdbkCmnts;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public CustFdbkRelt(int custDetId, int fdbkQuesId, String fdbkQuesResp,
			String fdbkCmnts, String crtId, Date crtTs, String updId, Date updTs) {
		this.custDetId = custDetId;
		this.fdbkQuesId = fdbkQuesId;
		this.fdbkQuesResp = fdbkQuesResp;
		this.fdbkCmnts = fdbkCmnts;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cust_det_id", nullable = false)
	public int getCustDetId() {
		return this.custDetId;
	}

	public void setCustDetId(int custDetId) {
		this.custDetId = custDetId;
	}

	@Column(name = "fdbk_ques_id", nullable = false)
	public int getFdbkQuesId() {
		return this.fdbkQuesId;
	}

	public void setFdbkQuesId(int fdbkQuesId) {
		this.fdbkQuesId = fdbkQuesId;
	}

	@Column(name = "fdbk_ques_resp", nullable = false, length = 200)
	public String getFdbkQuesResp() {
		return this.fdbkQuesResp;
	}

	public void setFdbkQuesResp(String fdbkQuesResp) {
		this.fdbkQuesResp = fdbkQuesResp;
	}

	/*@Column(name = "fdbk_cmnts", nullable = false, length = 200)
	public String getFdbkCmnts() {
		return this.fdbkCmnts;
	}

	public void setFdbkCmnts(String fdbkCmnts) {
		this.fdbkCmnts = fdbkCmnts;
	}*/

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
