package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;






/**
 * CustOrdDet generated by hbm2java
 */
@Entity
@Table(name = "cust_ord_det")
public class CustOrdDet implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer custBillId;
	private int ordNo;
	private Integer kitchenId;
	private CustDet custDet;
	//private Integer custDetId;
	private String ordDt;
	private String ordStDt;
	private String ordEndDt;
	private String ordTmstp;
	private int ordrStId;
	//private Integer mealTimeId;
	private PkgDur pkgDur;
	private MealTime mealTime;
	private FoodTyp foodTyp;
	//private int foodTypId;
	//private int mealTypId;
	private MenuTyp menuTyp;
	//private int pkgSizTypId;
	private PkgSizTyp pkgSize;
	private int pkgSizTypQty;
	private boolean cancelF;
	//private int pkgDurId;
	private WeekTyp weekTyp;
	//private int weekTypId;
	private Float ordBillAmnt;
	private int payModId;
	private Integer ordOrgnId;
	private MealTyp mealType;
	
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;
	
	private Integer addressId;

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cust_bill_id")
	public Integer getCustBillId() {
		return this.custBillId;
	}

	public void setCustBillId(Integer custBillId) {
		this.custBillId = custBillId;
	}

	@Column(name = "ord_no", nullable = false, length = 500)
	public int getOrdNo() {
		return this.ordNo;
	}

	public void setOrdNo(int ordNo) {
		this.ordNo = ordNo;
	}

	@Column(name = "kitchen_id")
	public Integer getKitchenId() {
		return this.kitchenId;
	}

	public void setKitchenId(Integer kitchenId) {
		this.kitchenId = kitchenId;
	}

	/*@Column(name = "cust_det_id")
	public Integer getCustDetId() {
		return this.custDetId;
	}

	public void setCustDetId(Integer custDetId) {
		this.custDetId = custDetId;
	}*/

	@Column(name = "ord_dt", length = 100)
	public String getOrdDt() {
		return this.ordDt;
	}

	public void setOrdDt(String ordDt) {
		this.ordDt = ordDt;
	}

	@Column(name = "ord_st_dt", length = 200)
	public String getOrdStDt() {
		return this.ordStDt;
	}

	public void setOrdStDt(String ordStDt) {
		this.ordStDt = ordStDt;
	}

	@Column(name = "ord_end_dt", length = 200)
	public String getOrdEndDt() {
		return this.ordEndDt;
	}

	public void setOrdEndDt(String ordEndDt) {
		this.ordEndDt = ordEndDt;
	}

	@Column(name = "ord_tmstp", length = 100)
	public String getOrdTmstp() {
		return this.ordTmstp;
	}

	public void setOrdTmstp(String ordTmstp) {
		this.ordTmstp = ordTmstp;
	}

	@Column(name = "ordr_st_id", nullable = false)
	public int getOrdrStId() {
		return this.ordrStId;
	}

	public void setOrdrStId(int ordrStId) {
		this.ordrStId = ordrStId;
	}

	/*@Column(name = "meal_time_id")
	public Integer getMealTimeId() {
		return this.mealTimeId;
	}

	public void setMealTimeId(Integer mealTimeId) {
		this.mealTimeId = mealTimeId;
	}*/

	/*@Column(name = "food_typ_id", nullable = false)
	public int getFoodTypId() {
		return this.foodTypId;
	}

	public void setFoodTypId(int foodTypId) {
		this.foodTypId = foodTypId;
	}*/

	/*@Column(name = "meal_typ_id", nullable = false)
	public int getMealTypId() {
		return this.mealTypId;
	}

	public void setMealTypId(int mealTypId) {
		this.mealTypId = mealTypId;
	}*/

	/*@Column(name = "pkg_siz_typ_id", nullable = false)
	public int getPkgSizTypId() {
		return this.pkgSizTypId;
	}

	public void setPkgSizTypId(int pkgSizTypId) {
		this.pkgSizTypId = pkgSizTypId;
	}
*/
	@Column(name = "pkg_siz_typ_qty", nullable = false)
	public int getPkgSizTypQty() {
		return this.pkgSizTypQty;
	}

	public void setPkgSizTypQty(int pkgSizTypQty) {
		this.pkgSizTypQty = pkgSizTypQty;
	}

	@Column(name = "cancel_f", nullable = false)
	public boolean isCancelF() {
		return this.cancelF;
	}

	public void setCancelF(boolean cancelF) {
		this.cancelF = cancelF;
	}

	/*@Column(name = "pkg_dur_id", nullable = false)
	public int getPkgDurId() {
		return this.pkgDurId;
	}

	public void setPkgDurId(int pkgDurId) {
		this.pkgDurId = pkgDurId;
	}*/

	/*@Column(name = "week_typ_id", nullable = false)
	public int getWeekTypId() {
		return this.weekTypId;
	}

	public void setWeekTypId(int weekTypId) {
		this.weekTypId = weekTypId;
	}
*/
	@Column(name = "ord_bill_amnt")
	public Float getOrdBillAmnt() {
		return this.ordBillAmnt;
	}

	public void setOrdBillAmnt(Float ordBillAmnt) {
		this.ordBillAmnt = ordBillAmnt;
	}

	@Column(name = "pay_mod_id")
	public int getPayModId() {
		return this.payModId;
	}

	public void setPayModId(int payModId) {
		this.payModId = payModId;
	}

	@Column(name = "ord_orgn_id")
	public Integer getOrdOrgnId() {
		return this.ordOrgnId;
	}

	public void setOrdOrgnId(Integer ordOrgnId) {
		this.ordOrgnId = ordOrgnId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", nullable = false, length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}
	
	

	@Column(name = "address_id")
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cust_det_id",nullable = false)
	public CustDet getCustDet() {
		return custDet;
	}

	public void setCustDet(CustDet custDet) {
		this.custDet = custDet;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "meal_time_id", nullable = false)
	public MealTime getMealTime() {
		return mealTime;
	}

	public void setMealTime(MealTime mealTime) {
		this.mealTime = mealTime;
	}
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "menu_typ_id", nullable = false)
	public MenuTyp getMenuTyp() {
		return menuTyp;
	}

	public void setMenuTyp(MenuTyp menuTyp) {
		this.menuTyp = menuTyp;
	}
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "food_typ_id", nullable = false)
	public FoodTyp getFoodTyp() {
		return foodTyp;
	}

	public void setFoodTyp(FoodTyp foodTyp) {
		this.foodTyp = foodTyp;
	}
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "pkg_dur_id", nullable = false)
	public PkgDur getPkgDur() {
		return pkgDur;
	}

	public void setPkgDur(PkgDur pkgDur) {
		this.pkgDur = pkgDur;
	}
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "week_typ_id", nullable = false)
	public WeekTyp getWeekTyp() {
		return weekTyp;
	}

	public void setWeekTyp(WeekTyp weekTyp) {
		this.weekTyp = weekTyp;
	}
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "pkg_siz_typ_id", nullable = false)
	public PkgSizTyp getPkgSize() {
		return pkgSize;
	}

	public void setPkgSize(PkgSizTyp pkgSize) {
		this.pkgSize = pkgSize;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "meal_typ_id", nullable = false)
	public MealTyp getMealType() {
		return mealType;
	}

	public void setMealType(MealTyp mealType) {
		this.mealType = mealType;
	}

	

	

}
