package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * DelvChrg generated by hbm2java
 */
@Entity
@Table(name = "delv_chrg")
public class DelvChrg implements java.io.Serializable {
	

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	
	private String delvDesc;
	
	private Integer delvChrg;
	@JsonIgnore
	private int delvChrgF;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;
	
	@JsonIgnore
	private Set<PkgSizTyp> pkgSizTyp = new HashSet<PkgSizTyp>();

	public DelvChrg() {
	}

	public DelvChrg(String delvDesc, int delvChrgF, Date crtTs,
			String crtId, String updId) {
		this.delvDesc = delvDesc;
		this.delvChrgF = delvChrgF;
		this.crtTs = crtTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	public DelvChrg(String delvDesc, Integer delvChrg, int delvChrgF,
			Date crtTs, Date updTs, String crtId, String updId) {
		this.delvDesc = delvDesc;
		this.delvChrg = delvChrg;
		this.delvChrgF = delvChrgF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "delv_desc", nullable = false, length = 200)
	public String getDelvDesc() {
		return this.delvDesc;
	}

	public void setDelvDesc(String delvDesc) {
		this.delvDesc = delvDesc;
	}

	@Column(name = "delv_chrg")
	public Integer getDelvChrg() {
		return this.delvChrg;
	}

	public void setDelvChrg(Integer delvChrg) {
		this.delvChrg = delvChrg;
	}

	@Column(name = "delv_chrg_f", nullable = false)
	public int isDelvChrgF() {
		return this.delvChrgF;
	}

	public void setDelvChrgF(int delvChrgF) {
		this.delvChrgF = delvChrgF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", nullable = false, length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@OneToMany(mappedBy = "delvChrg")
	public Set<PkgSizTyp> getPkgSizTyp() {
		return pkgSizTyp;
	}

	public void setPkgSizTyp(Set<PkgSizTyp> pkgSizTyp) {
		this.pkgSizTyp = pkgSizTyp;
	}
	
}
