package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DeviceTab generated by hbm2java
 */
@Entity
@Table(name = "device_tab", catalog = "spiceboxcoupon")
public class DeviceTab implements java.io.Serializable {

	private Integer id;
	private String modelNo;
	private String uniqueCode;
	private String deveiceName;

	public DeviceTab() {
	}

	public DeviceTab(String modelNo, String uniqueCode, String deveiceName) {
		this.modelNo = modelNo;
		this.uniqueCode = uniqueCode;
		this.deveiceName = deveiceName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "model_no")
	public String getModelNo() {
		return this.modelNo;
	}

	public void setModelNo(String modelNo) {
		this.modelNo = modelNo;
	}

	@Column(name = "unique_code")
	public String getUniqueCode() {
		return this.uniqueCode;
	}

	public void setUniqueCode(String uniqueCode) {
		this.uniqueCode = uniqueCode;
	}

	@Column(name = "deveice_name")
	public String getDeveiceName() {
		return this.deveiceName;
	}

	public void setDeveiceName(String deveiceName) {
		this.deveiceName = deveiceName;
	}

}
