package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Disc generated by hbm2java
 */
@Entity
@Table(name = "disc", catalog = "spiceboxcoupon")
public class Disc implements java.io.Serializable {

	private Integer id;
	private int disCode;
	private String disDesc;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public Disc() {
	}

	public Disc(int disCode, String disDesc, Date crtTs, Date updTs,
			String crtId) {
		this.disCode = disCode;
		this.disDesc = disDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
	}

	public Disc(int disCode, String disDesc, Date crtTs, Date updTs,
			String crtId, String updId) {
		this.disCode = disCode;
		this.disDesc = disDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "dis_code", nullable = false)
	public int getDisCode() {
		return this.disCode;
	}

	public void setDisCode(int disCode) {
		this.disCode = disCode;
	}

	@Column(name = "dis_desc", nullable = false, length = 65535)
	public String getDisDesc() {
		return this.disDesc;
	}

	public void setDisDesc(String disDesc) {
		this.disDesc = disDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
