package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailTmplt generated by hbm2java
 */
@Entity
@Table(name = "email_tmplt", catalog = "starfoodlocal")
public class EmailTmplt implements java.io.Serializable {

	private Integer id;
	private Integer emailTypId;
	private String emailTypDesc;
	private byte emailTypF;
	private String emailSubj;
	private String emailBody;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public EmailTmplt() {
	}

	public EmailTmplt(String emailTypDesc, byte emailTypF, String emailSubj,
			String emailBody, String crtId, Date crtTs) {
		this.emailTypDesc = emailTypDesc;
		this.emailTypF = emailTypF;
		this.emailSubj = emailSubj;
		this.emailBody = emailBody;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public EmailTmplt(Integer emailTypId, String emailTypDesc, byte emailTypF,
			String emailSubj, String emailBody, String crtId, Date crtTs,
			String updId, Date updTs) {
		this.emailTypId = emailTypId;
		this.emailTypDesc = emailTypDesc;
		this.emailTypF = emailTypF;
		this.emailSubj = emailSubj;
		this.emailBody = emailBody;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email_typ_id")
	public Integer getEmailTypId() {
		return this.emailTypId;
	}

	public void setEmailTypId(Integer emailTypId) {
		this.emailTypId = emailTypId;
	}

	@Column(name = "email_typ_desc", nullable = false, length = 100)
	public String getEmailTypDesc() {
		return this.emailTypDesc;
	}

	public void setEmailTypDesc(String emailTypDesc) {
		this.emailTypDesc = emailTypDesc;
	}

	@Column(name = "email_typ_f", nullable = false)
	public byte getEmailTypF() {
		return this.emailTypF;
	}

	public void setEmailTypF(byte emailTypF) {
		this.emailTypF = emailTypF;
	}

	@Column(name = "email_subj", nullable = false, length = 200)
	public String getEmailSubj() {
		return this.emailSubj;
	}

	public void setEmailSubj(String emailSubj) {
		this.emailSubj = emailSubj;
	}

	@Column(name = "email_body", nullable = false, length = 2000)
	public String getEmailBody() {
		return this.emailBody;
	}

	public void setEmailBody(String emailBody) {
		this.emailBody = emailBody;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
