package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EorderConfig generated by hbm2java
 */
@Entity
@Table(name = "eorder_config", catalog = "starfoodlocal")
public class EorderConfig implements java.io.Serializable {

	private Integer id;
	private String functionalityName;
	private boolean flag;

	public EorderConfig() {
	}

	public EorderConfig(boolean flag) {
		this.flag = flag;
	}

	public EorderConfig(String functionalityName, boolean flag) {
		this.functionalityName = functionalityName;
		this.flag = flag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "functionality_name", length = 500)
	public String getFunctionalityName() {
		return this.functionalityName;
	}

	public void setFunctionalityName(String functionalityName) {
		this.functionalityName = functionalityName;
	}

	@Column(name = "flag", nullable = false)
	public boolean isFlag() {
		return this.flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

}
