package com.nibble.starfood.hibernatemodel;

import static javax.persistence.GenerationType.IDENTITY;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;


/**
 * CupnDet generated by hbm2java
 */
@Entity
@Table(name = "eorder_client_detail")
public class EorderClientDetail implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String clientName;
	private String clientEmailId;
	private String clientPassword;
	private String clientSmtp;
	private String clientContNum;
	private String clientAddr;

	
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@Column(name = "client_name", length = 45)
	public String getClientName() {
		return clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}
	@Column(name = "client_email_id", length = 45)
	public String getClientEmailId() {
		return clientEmailId;
	}

	public void setClientEmailId(String clientEmailId) {
		this.clientEmailId = clientEmailId;
	}
	@Column(name = "client_pwd", length = 45)
	public String getClientPassword() {
		return clientPassword;
	}

	public void setClientPassword(String clientPassword) {
		this.clientPassword = clientPassword;
	}
	@Column(name = "client_smtp", length = 45)
	public String getClientSmtp() {
		return clientSmtp;
	}

	public void setClientSmtp(String clientSmtp) {
		this.clientSmtp = clientSmtp;
	}
	@Column(name = "client_contact_no", length = 45)
	public String getClientContNum() {
		return clientContNum;
	}

	public void setClientContNum(String clientContNum) {
		this.clientContNum = clientContNum;
	}
	@Column(name = "client_address", length = 45)
	public String getClientAddr() {
		return clientAddr;
	}

	public void setClientAddr(String clientAddr) {
		this.clientAddr = clientAddr;
	}

	
	
}


