package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * FdbkQues generated by hbm2java
 */
@Entity
@Table(name = "fdbk_ques")
public class FdbkQues implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String fdbkQuesDesc;
	@JsonIgnore
	private int fdbkQuesF;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private String updId;
	@JsonIgnore
	private Date updTs;

	public FdbkQues() {
	}

	public FdbkQues(String fdbkQuesDesc, int fdbkQuesF, String crtId,
			Date crtTs) {
		this.fdbkQuesDesc = fdbkQuesDesc;
		this.fdbkQuesF = fdbkQuesF;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public FdbkQues(String fdbkQuesDesc, int fdbkQuesF, String crtId,
			Date crtTs, String updId, Date updTs) {
		this.fdbkQuesDesc = fdbkQuesDesc;
		this.fdbkQuesF = fdbkQuesF;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fdbk_ques_desc", nullable = false, length = 200)
	public String getFdbkQuesDesc() {
		return this.fdbkQuesDesc;
	}

	public void setFdbkQuesDesc(String fdbkQuesDesc) {
		this.fdbkQuesDesc = fdbkQuesDesc;
	}

	@Column(name = "fdbk_ques_f", nullable = false)
	public int isFdbkQuesF() {
		return this.fdbkQuesF;
	}

	public void setFdbkQuesF(int fdbkQuesF) {
		this.fdbkQuesF = fdbkQuesF;
	}

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
