package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;



/**
 * FoodTyp generated by hbm2java
 */
@Entity
@Table(name = "food_typ")
public class FoodTyp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	 @JsonIgnore
	private Integer foodTypeCode;
	private String foodTypeDesc;
	 @JsonIgnore
	private int foodTypeVisF;
	 @JsonIgnore
	private Date crtTs;
	 @JsonIgnore
	private Date updTs;
	 @JsonIgnore
	private String crtId;
	 @JsonIgnore
	private String updId;
	/*@JsonIgnore
	private Set<CustOrdDet> orders = new HashSet<CustOrdDet>();*/
	@JsonIgnore
	private Set<PkgSizTyp> pkgSizTyp = new HashSet<PkgSizTyp>();
	public FoodTyp() {
	}

	public FoodTyp(String foodTypeDesc, int foodTypeVisF, Date crtTs,
			String crtId) {
		this.foodTypeDesc = foodTypeDesc;
		this.foodTypeVisF = foodTypeVisF;
		this.crtTs = crtTs;
		this.crtId = crtId;
	}

	public FoodTyp(Integer foodTypeCode, String foodTypeDesc,
			int foodTypeVisF, Date crtTs, Date updTs, String crtId,
			String updId) {
		this.foodTypeCode = foodTypeCode;
		this.foodTypeDesc = foodTypeDesc;
		this.foodTypeVisF = foodTypeVisF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "food_type_code")
	public Integer getFoodTypeCode() {
		return this.foodTypeCode;
	}

	public void setFoodTypeCode(Integer foodTypeCode) {
		this.foodTypeCode = foodTypeCode;
	}

	@Column(name = "food_type_desc", nullable = false)
	public String getFoodTypeDesc() {
		return this.foodTypeDesc;
	}

	public void setFoodTypeDesc(String foodTypeDesc) {
		this.foodTypeDesc = foodTypeDesc;
	}

	@Column(name = "food_type_vis_f", nullable = false)
	public int isFoodTypeVisF() {
		return this.foodTypeVisF;
	}

	public void setFoodTypeVisF(int foodTypeVisF) {
		this.foodTypeVisF = foodTypeVisF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}
  /* @OneToMany(fetch = FetchType.LAZY, mappedBy = "foodTyp")
	public Set<CustOrdDet> getOrders() {
		return orders;
	}

	public void setOrders(Set<CustOrdDet> orders) {
		this.orders = orders;
	}*/
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "foodtyp")
	public Set<PkgSizTyp> getPkgSizTyp() {
		return pkgSizTyp;
	}

	public void setPkgSizTyp(Set<PkgSizTyp> pkgSizTyp) {
		this.pkgSizTyp = pkgSizTyp;
	}
	

}
