package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FoodItm generated by hbm2java
 */
@Entity
@Table(name = "food_itm", catalog = "spiceboxcoupon")
public class FoodItm implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer cusId;
	private Integer foodTypeId;
	private int foodCatgTypCode;
	private Integer foodItmCode;
	private String servCnt;
	private int servCntFlag;
	private Integer foodItmShortCode;
	private String foodItmShortNameEn;
	private String foodItmNameEn;
	private String foodItmShortNameHn;
	private String foodItmNameHn;
	private String foodItmShortNameUr;
	private String foodItmNameUr;
	private String image;
	private String imageThumb;
	private String foodItmDescEn;
	private String foodItmDescHn;
	private String foodItmDescUr;
	private String foodItmPrc;
	private Integer foodItmSrlNo;
	private Integer foodItmTstCode;
	private String foodItmPrepTime;
	private Integer suffCount;
	private Integer comboOfrCode;
	private Integer ofrCode;
	private Integer chfSplCode;
	private String calVal;
	private Boolean foodItmVisF;
	private Boolean fbF;
	private Boolean twF;
	private Boolean glF;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;
	private Integer mealTimeCode;

	public FoodItm() {
	}

	public FoodItm(int foodCatgTypCode, String servCnt, int servCntFlag,
			String foodItmNameEn, String foodItmPrc, Date crtTs) {
		this.foodCatgTypCode = foodCatgTypCode;
		this.servCnt = servCnt;
		this.servCntFlag = servCntFlag;
		this.foodItmNameEn = foodItmNameEn;
		this.foodItmPrc = foodItmPrc;
		this.crtTs = crtTs;
	}

	public FoodItm(Integer cusId, Integer foodTypeId, int foodCatgTypCode,
			Integer foodItmCode, String servCnt, int servCntFlag,
			Integer foodItmShortCode, String foodItmShortNameEn,
			String foodItmNameEn, String foodItmShortNameHn,
			String foodItmNameHn, String foodItmShortNameUr,
			String foodItmNameUr, String image, String imageThumb,
			String foodItmDescEn, String foodItmDescHn, String foodItmDescUr,
			String foodItmPrc, Integer foodItmSrlNo, Integer foodItmTstCode,
			String foodItmPrepTime, Integer suffCount, Integer comboOfrCode,
			Integer ofrCode, Integer chfSplCode, String calVal,
			Boolean foodItmVisF, Boolean fbF, Boolean twF, Boolean glF,
			Date crtTs, Date updTs, String crtId, String updId,
			Integer mealTimeCode) {
		this.cusId = cusId;
		this.foodTypeId = foodTypeId;
		this.foodCatgTypCode = foodCatgTypCode;
		this.foodItmCode = foodItmCode;
		this.servCnt = servCnt;
		this.servCntFlag = servCntFlag;
		this.foodItmShortCode = foodItmShortCode;
		this.foodItmShortNameEn = foodItmShortNameEn;
		this.foodItmNameEn = foodItmNameEn;
		this.foodItmShortNameHn = foodItmShortNameHn;
		this.foodItmNameHn = foodItmNameHn;
		this.foodItmShortNameUr = foodItmShortNameUr;
		this.foodItmNameUr = foodItmNameUr;
		this.image = image;
		this.imageThumb = imageThumb;
		this.foodItmDescEn = foodItmDescEn;
		this.foodItmDescHn = foodItmDescHn;
		this.foodItmDescUr = foodItmDescUr;
		this.foodItmPrc = foodItmPrc;
		this.foodItmSrlNo = foodItmSrlNo;
		this.foodItmTstCode = foodItmTstCode;
		this.foodItmPrepTime = foodItmPrepTime;
		this.suffCount = suffCount;
		this.comboOfrCode = comboOfrCode;
		this.ofrCode = ofrCode;
		this.chfSplCode = chfSplCode;
		this.calVal = calVal;
		this.foodItmVisF = foodItmVisF;
		this.fbF = fbF;
		this.twF = twF;
		this.glF = glF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
		this.mealTimeCode = mealTimeCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cus_id")
	public Integer getCusId() {
		return this.cusId;
	}

	public void setCusId(Integer cusId) {
		this.cusId = cusId;
	}

	@Column(name = "food_type_id")
	public Integer getFoodTypeId() {
		return this.foodTypeId;
	}

	public void setFoodTypeId(Integer foodTypeId) {
		this.foodTypeId = foodTypeId;
	}

	@Column(name = "food_catg_typ_code", nullable = false)
	public int getFoodCatgTypCode() {
		return this.foodCatgTypCode;
	}

	public void setFoodCatgTypCode(int foodCatgTypCode) {
		this.foodCatgTypCode = foodCatgTypCode;
	}

	@Column(name = "food_itm_code")
	public Integer getFoodItmCode() {
		return this.foodItmCode;
	}

	public void setFoodItmCode(Integer foodItmCode) {
		this.foodItmCode = foodItmCode;
	}

	@Column(name = "serv_cnt", nullable = false, length = 100)
	public String getServCnt() {
		return this.servCnt;
	}

	public void setServCnt(String servCnt) {
		this.servCnt = servCnt;
	}

	@Column(name = "serv_cnt_flag", nullable = false)
	public int getServCntFlag() {
		return this.servCntFlag;
	}

	public void setServCntFlag(int servCntFlag) {
		this.servCntFlag = servCntFlag;
	}

	@Column(name = "food_itm_short_code")
	public Integer getFoodItmShortCode() {
		return this.foodItmShortCode;
	}

	public void setFoodItmShortCode(Integer foodItmShortCode) {
		this.foodItmShortCode = foodItmShortCode;
	}

	@Column(name = "food_itm_short_name_en", length = 50)
	public String getFoodItmShortNameEn() {
		return this.foodItmShortNameEn;
	}

	public void setFoodItmShortNameEn(String foodItmShortNameEn) {
		this.foodItmShortNameEn = foodItmShortNameEn;
	}

	@Column(name = "food_itm_name_en", nullable = false, length = 150)
	public String getFoodItmNameEn() {
		return this.foodItmNameEn;
	}

	public void setFoodItmNameEn(String foodItmNameEn) {
		this.foodItmNameEn = foodItmNameEn;
	}

	@Column(name = "food_itm_short_name_hn", length = 50)
	public String getFoodItmShortNameHn() {
		return this.foodItmShortNameHn;
	}

	public void setFoodItmShortNameHn(String foodItmShortNameHn) {
		this.foodItmShortNameHn = foodItmShortNameHn;
	}

	@Column(name = "food_itm_name_hn", length = 150)
	public String getFoodItmNameHn() {
		return this.foodItmNameHn;
	}

	public void setFoodItmNameHn(String foodItmNameHn) {
		this.foodItmNameHn = foodItmNameHn;
	}

	@Column(name = "food_itm_short_name_ur", length = 50)
	public String getFoodItmShortNameUr() {
		return this.foodItmShortNameUr;
	}

	public void setFoodItmShortNameUr(String foodItmShortNameUr) {
		this.foodItmShortNameUr = foodItmShortNameUr;
	}

	@Column(name = "food_itm_name_ur", length = 150)
	public String getFoodItmNameUr() {
		return this.foodItmNameUr;
	}

	public void setFoodItmNameUr(String foodItmNameUr) {
		this.foodItmNameUr = foodItmNameUr;
	}

	@Column(name = "image", length = 254)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "image_thumb", length = 254)
	public String getImageThumb() {
		return this.imageThumb;
	}

	public void setImageThumb(String imageThumb) {
		this.imageThumb = imageThumb;
	}

	@Column(name = "food_itm_desc_en", length = 250)
	public String getFoodItmDescEn() {
		return this.foodItmDescEn;
	}

	public void setFoodItmDescEn(String foodItmDescEn) {
		this.foodItmDescEn = foodItmDescEn;
	}

	@Column(name = "food_itm_desc_hn", length = 250)
	public String getFoodItmDescHn() {
		return this.foodItmDescHn;
	}

	public void setFoodItmDescHn(String foodItmDescHn) {
		this.foodItmDescHn = foodItmDescHn;
	}

	@Column(name = "food_itm_desc_ur", length = 250)
	public String getFoodItmDescUr() {
		return this.foodItmDescUr;
	}

	public void setFoodItmDescUr(String foodItmDescUr) {
		this.foodItmDescUr = foodItmDescUr;
	}

	@Column(name = "food_itm_prc", nullable = false)
	public String getFoodItmPrc() {
		return this.foodItmPrc;
	}

	public void setFoodItmPrc(String foodItmPrc) {
		this.foodItmPrc = foodItmPrc;
	}

	@Column(name = "food_itm_srl_no")
	public Integer getFoodItmSrlNo() {
		return this.foodItmSrlNo;
	}

	public void setFoodItmSrlNo(Integer foodItmSrlNo) {
		this.foodItmSrlNo = foodItmSrlNo;
	}

	@Column(name = "food_itm_tst_code")
	public Integer getFoodItmTstCode() {
		return this.foodItmTstCode;
	}

	public void setFoodItmTstCode(Integer foodItmTstCode) {
		this.foodItmTstCode = foodItmTstCode;
	}

	@Column(name = "food_itm_prep_time", length = 100)
	public String getFoodItmPrepTime() {
		return this.foodItmPrepTime;
	}

	public void setFoodItmPrepTime(String foodItmPrepTime) {
		this.foodItmPrepTime = foodItmPrepTime;
	}

	@Column(name = "suff_count")
	public Integer getSuffCount() {
		return this.suffCount;
	}

	public void setSuffCount(Integer suffCount) {
		this.suffCount = suffCount;
	}

	@Column(name = "combo_ofr_code")
	public Integer getComboOfrCode() {
		return this.comboOfrCode;
	}

	public void setComboOfrCode(Integer comboOfrCode) {
		this.comboOfrCode = comboOfrCode;
	}

	@Column(name = "ofr_code")
	public Integer getOfrCode() {
		return this.ofrCode;
	}

	public void setOfrCode(Integer ofrCode) {
		this.ofrCode = ofrCode;
	}

	@Column(name = "chf_spl_code")
	public Integer getChfSplCode() {
		return this.chfSplCode;
	}

	public void setChfSplCode(Integer chfSplCode) {
		this.chfSplCode = chfSplCode;
	}

	@Column(name = "cal_val", length = 65535)
	public String getCalVal() {
		return this.calVal;
	}

	public void setCalVal(String calVal) {
		this.calVal = calVal;
	}

	@Column(name = "food_itm_vis_f")
	public Boolean getFoodItmVisF() {
		return this.foodItmVisF;
	}

	public void setFoodItmVisF(Boolean foodItmVisF) {
		this.foodItmVisF = foodItmVisF;
	}

	@Column(name = "fb_f")
	public Boolean getFbF() {
		return this.fbF;
	}

	public void setFbF(Boolean fbF) {
		this.fbF = fbF;
	}

	@Column(name = "tw_f")
	public Boolean getTwF() {
		return this.twF;
	}

	public void setTwF(Boolean twF) {
		this.twF = twF;
	}

	@Column(name = "gl_f")
	public Boolean getGlF() {
		return this.glF;
	}

	public void setGlF(Boolean glF) {
		this.glF = glF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "meal_time_code")
	public Integer getMealTimeCode() {
		return this.mealTimeCode;
	}

	public void setMealTimeCode(Integer mealTimeCode) {
		this.mealTimeCode = mealTimeCode;
	}

}
