package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FoodItmTst generated by hbm2java
 */
@Entity
@Table(name = "food_itm_tst")
public class FoodItmTst implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int foodItmTstCode;
	private String foodItmTstDesc;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public FoodItmTst() {
	}

	public FoodItmTst(int foodItmTstCode, String foodItmTstDesc, Date crtTs,
			Date updTs, String crtId) {
		this.foodItmTstCode = foodItmTstCode;
		this.foodItmTstDesc = foodItmTstDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
	}

	public FoodItmTst(int foodItmTstCode, String foodItmTstDesc, Date crtTs,
			Date updTs, String crtId, String updId) {
		this.foodItmTstCode = foodItmTstCode;
		this.foodItmTstDesc = foodItmTstDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "food_itm_tst_code", nullable = false)
	public int getFoodItmTstCode() {
		return this.foodItmTstCode;
	}

	public void setFoodItmTstCode(int foodItmTstCode) {
		this.foodItmTstCode = foodItmTstCode;
	}

	@Column(name = "food_itm_tst_desc", nullable = false, length = 65535)
	public String getFoodItmTstDesc() {
		return this.foodItmTstDesc;
	}

	public void setFoodItmTstDesc(String foodItmTstDesc) {
		this.foodItmTstDesc = foodItmTstDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
