package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GuestTablRelt generated by hbm2java
 */
@Entity
@Table(name = "guest_tabl_relt", catalog = "spiceboxcoupon")
public class GuestTablRelt implements java.io.Serializable {

	private Integer id;
	private int guestId;
	private int tablId;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public GuestTablRelt() {
	}

	public GuestTablRelt(int guestId, int tablId, Date crtTs, String crtId) {
		this.guestId = guestId;
		this.tablId = tablId;
		this.crtTs = crtTs;
		this.crtId = crtId;
	}

	public GuestTablRelt(int guestId, int tablId, Date crtTs, Date updTs,
			String crtId, String updId) {
		this.guestId = guestId;
		this.tablId = tablId;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "guest_id", nullable = false)
	public int getGuestId() {
		return this.guestId;
	}

	public void setGuestId(int guestId) {
		this.guestId = guestId;
	}

	@Column(name = "tabl_id", nullable = false)
	public int getTablId() {
		return this.tablId;
	}

	public void setTablId(int tablId) {
		this.tablId = tablId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
