package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GuestCustDet generated by hbm2java
 */
@Entity
@Table(name = "guest_cust_det", catalog = "spiceboxcoupon")
public class GuestCustDet implements java.io.Serializable {

	private Integer id;
	private String custName;
	private String cntcNo;
	private String emailId;
	private String crtTs;
	private String crtId;
	private String updTs;
	private String updId;
	private String cupnRedmAmnt;
	private String custCode;

	public GuestCustDet() {
	}

	public GuestCustDet(String custName, String cntcNo, String emailId,
			String crtTs, String crtId, String updTs, String updId,
			String cupnRedmAmnt, String custCode) {
		this.custName = custName;
		this.cntcNo = cntcNo;
		this.emailId = emailId;
		this.crtTs = crtTs;
		this.crtId = crtId;
		this.updTs = updTs;
		this.updId = updId;
		this.cupnRedmAmnt = cupnRedmAmnt;
		this.custCode = custCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cust_name", length = 100)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "cntc_no", length = 100)
	public String getCntcNo() {
		return this.cntcNo;
	}

	public void setCntcNo(String cntcNo) {
		this.cntcNo = cntcNo;
	}

	@Column(name = "email_id", length = 100)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "crt_ts", length = 100)
	public String getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(String crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_ts", length = 100)
	public String getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(String updTs) {
		this.updTs = updTs;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "cupn_redm_amnt", length = 100)
	public String getCupnRedmAmnt() {
		return this.cupnRedmAmnt;
	}

	public void setCupnRedmAmnt(String cupnRedmAmnt) {
		this.cupnRedmAmnt = cupnRedmAmnt;
	}

	@Column(name = "cust_code", length = 100)
	public String getCustCode() {
		return this.custCode;
	}

	public void setCustCode(String custCode) {
		this.custCode = custCode;
	}

}
