package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IvrData generated by hbm2java
 */
@Entity
@Table(name = "ivr_data", catalog = "starfoodlocal")
public class IvrData implements java.io.Serializable {

	private Integer id;
	private String ivrClientName;
	private String ivrId;
	private String direction;
	private String type;
	private String chatNo;
	private String fromNo;
	private String fromName;
	private String toNo;
	private String toName;
	private String status;
	private String strtTime;
	private String endTime;
	private String billableDurn;
	private String price;
	private String recrdngUrl;
	private String priceDet;
	private String groupName;
	private String fromCrcle;
	private String toCrcle;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public IvrData() {
	}

	public IvrData(String crtId, Date crtTs) {
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public IvrData(String ivrClientName, String ivrId, String direction,
			String type, String chatNo, String fromNo, String fromName,
			String toNo, String toName, String status, String strtTime,
			String endTime, String billableDurn, String price,
			String recrdngUrl, String priceDet, String groupName,
			String fromCrcle, String toCrcle, String crtId, Date crtTs,
			String updId, Date updTs) {
		this.ivrClientName = ivrClientName;
		this.ivrId = ivrId;
		this.direction = direction;
		this.type = type;
		this.chatNo = chatNo;
		this.fromNo = fromNo;
		this.fromName = fromName;
		this.toNo = toNo;
		this.toName = toName;
		this.status = status;
		this.strtTime = strtTime;
		this.endTime = endTime;
		this.billableDurn = billableDurn;
		this.price = price;
		this.recrdngUrl = recrdngUrl;
		this.priceDet = priceDet;
		this.groupName = groupName;
		this.fromCrcle = fromCrcle;
		this.toCrcle = toCrcle;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ivr_client_name", length = 500)
	public String getIvrClientName() {
		return this.ivrClientName;
	}

	public void setIvrClientName(String ivrClientName) {
		this.ivrClientName = ivrClientName;
	}

	@Column(name = "ivr_id", length = 1000)
	public String getIvrId() {
		return this.ivrId;
	}

	public void setIvrId(String ivrId) {
		this.ivrId = ivrId;
	}

	@Column(name = "direction", length = 500)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "type", length = 500)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "chat_no", length = 100)
	public String getChatNo() {
		return this.chatNo;
	}

	public void setChatNo(String chatNo) {
		this.chatNo = chatNo;
	}

	@Column(name = "from_no", length = 100)
	public String getFromNo() {
		return this.fromNo;
	}

	public void setFromNo(String fromNo) {
		this.fromNo = fromNo;
	}

	@Column(name = "from_name", length = 1000)
	public String getFromName() {
		return this.fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	@Column(name = "to_no", length = 100)
	public String getToNo() {
		return this.toNo;
	}

	public void setToNo(String toNo) {
		this.toNo = toNo;
	}

	@Column(name = "to_name", length = 1000)
	public String getToName() {
		return this.toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	@Column(name = "status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "strt_time", length = 100)
	public String getStrtTime() {
		return this.strtTime;
	}

	public void setStrtTime(String strtTime) {
		this.strtTime = strtTime;
	}

	@Column(name = "end_time", length = 100)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "billable_durn", length = 100)
	public String getBillableDurn() {
		return this.billableDurn;
	}

	public void setBillableDurn(String billableDurn) {
		this.billableDurn = billableDurn;
	}

	@Column(name = "price", length = 100)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "recrdng_url", length = 1000)
	public String getRecrdngUrl() {
		return this.recrdngUrl;
	}

	public void setRecrdngUrl(String recrdngUrl) {
		this.recrdngUrl = recrdngUrl;
	}

	@Column(name = "price_det", length = 500)
	public String getPriceDet() {
		return this.priceDet;
	}

	public void setPriceDet(String priceDet) {
		this.priceDet = priceDet;
	}

	@Column(name = "group_name", length = 200)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "from_crcle", length = 10)
	public String getFromCrcle() {
		return this.fromCrcle;
	}

	public void setFromCrcle(String fromCrcle) {
		this.fromCrcle = fromCrcle;
	}

	@Column(name = "to_crcle", length = 10)
	public String getToCrcle() {
		return this.toCrcle;
	}

	public void setToCrcle(String toCrcle) {
		this.toCrcle = toCrcle;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
