package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KitchenFoodRelt generated by hbm2java
 */
@Entity
@Table(name = "kitchen_food_relt", catalog = "starfoodlocal")
public class KitchenFoodRelt implements java.io.Serializable {

	private Integer id;
	private int kitchenId;
	private int foodItmId;
	private Boolean foodItmF;
	private String mealTimeId;

	public KitchenFoodRelt() {
	}

	public KitchenFoodRelt(int kitchenId, int foodItmId, String mealTimeId) {
		this.kitchenId = kitchenId;
		this.foodItmId = foodItmId;
		this.mealTimeId = mealTimeId;
	}

	public KitchenFoodRelt(int kitchenId, int foodItmId, Boolean foodItmF,
			String mealTimeId) {
		this.kitchenId = kitchenId;
		this.foodItmId = foodItmId;
		this.foodItmF = foodItmF;
		this.mealTimeId = mealTimeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "KITCHEN_ID", nullable = false)
	public int getKitchenId() {
		return this.kitchenId;
	}

	public void setKitchenId(int kitchenId) {
		this.kitchenId = kitchenId;
	}

	@Column(name = "FOOD_ITM_ID", nullable = false)
	public int getFoodItmId() {
		return this.foodItmId;
	}

	public void setFoodItmId(int foodItmId) {
		this.foodItmId = foodItmId;
	}

	@Column(name = "FOOD_ITM_F")
	public Boolean getFoodItmF() {
		return this.foodItmF;
	}

	public void setFoodItmF(Boolean foodItmF) {
		this.foodItmF = foodItmF;
	}

	@Column(name = "meal_time_id", nullable = false, length = 45)
	public String getMealTimeId() {
		return this.mealTimeId;
	}

	public void setMealTimeId(String mealTimeId) {
		this.mealTimeId = mealTimeId;
	}

}
