package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kitchen generated by hbm2java
 */
@Entity
@Table(name = "kitchen", catalog = "starfoodlocal")
public class Kitchen implements java.io.Serializable {

	private Integer id;
	private String kitchenName;
	private Integer areaId;
	private String areaLat;
	private String areaLong;
	private Integer chefId;
	private String cntcNo;
	private boolean kitchenF;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public Kitchen() {
	}

	public Kitchen(String kitchenName, boolean kitchenF, Date crtTs,
			Date updTs, String crtId) {
		this.kitchenName = kitchenName;
		this.kitchenF = kitchenF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
	}

	public Kitchen(String kitchenName, Integer areaId, String areaLat,
			String areaLong, Integer chefId, String cntcNo, boolean kitchenF,
			Date crtTs, Date updTs, String crtId, String updId) {
		this.kitchenName = kitchenName;
		this.areaId = areaId;
		this.areaLat = areaLat;
		this.areaLong = areaLong;
		this.chefId = chefId;
		this.cntcNo = cntcNo;
		this.kitchenF = kitchenF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "KITCHEN_NAME", nullable = false, length = 100)
	public String getKitchenName() {
		return this.kitchenName;
	}

	public void setKitchenName(String kitchenName) {
		this.kitchenName = kitchenName;
	}

	@Column(name = "AREA_ID")
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@Column(name = "AREA_LAT", length = 100)
	public String getAreaLat() {
		return this.areaLat;
	}

	public void setAreaLat(String areaLat) {
		this.areaLat = areaLat;
	}

	@Column(name = "AREA_LONG", length = 100)
	public String getAreaLong() {
		return this.areaLong;
	}

	public void setAreaLong(String areaLong) {
		this.areaLong = areaLong;
	}

	@Column(name = "CHEF_ID")
	public Integer getChefId() {
		return this.chefId;
	}

	public void setChefId(Integer chefId) {
		this.chefId = chefId;
	}

	@Column(name = "CNTC_NO", length = 100)
	public String getCntcNo() {
		return this.cntcNo;
	}

	public void setCntcNo(String cntcNo) {
		this.cntcNo = cntcNo;
	}

	@Column(name = "KITCHEN_F", nullable = false)
	public boolean isKitchenF() {
		return this.kitchenF;
	}

	public void setKitchenF(boolean kitchenF) {
		this.kitchenF = kitchenF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
