package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lang generated by hbm2java
 */
@Entity
@Table(name = "lang", catalog = "starfoodlocal")
public class Lang implements java.io.Serializable {

	private Integer id;
	private int langCode;
	private String langDesc;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public Lang() {
	}

	public Lang(int langCode, String langDesc, Date crtTs, Date updTs,
			String crtId) {
		this.langCode = langCode;
		this.langDesc = langDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
	}

	public Lang(int langCode, String langDesc, Date crtTs, Date updTs,
			String crtId, String updId) {
		this.langCode = langCode;
		this.langDesc = langDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "lang_code", nullable = false)
	public int getLangCode() {
		return this.langCode;
	}

	public void setLangCode(int langCode) {
		this.langCode = langCode;
	}

	@Column(name = "lang_desc", nullable = false, length = 65535)
	public String getLangDesc() {
		return this.langDesc;
	}

	public void setLangDesc(String langDesc) {
		this.langDesc = langDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
