package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Liqtax generated by hbm2java
 */
@Entity
@Table(name = "liqtax", catalog = "spiceboxcoupon")
public class Liqtax implements java.io.Serializable {

	private Integer id;
	private int taxCode;
	private String taxDesc;
	private String taxPnct;
	private byte taxVisF;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public Liqtax() {
	}

	public Liqtax(int taxCode, String taxDesc, String taxPnct, byte taxVisF,
			Date crtTs, Date updTs) {
		this.taxCode = taxCode;
		this.taxDesc = taxDesc;
		this.taxPnct = taxPnct;
		this.taxVisF = taxVisF;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public Liqtax(int taxCode, String taxDesc, String taxPnct, byte taxVisF,
			Date crtTs, Date updTs, String crtId, String updId) {
		this.taxCode = taxCode;
		this.taxDesc = taxDesc;
		this.taxPnct = taxPnct;
		this.taxVisF = taxVisF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tax_code", nullable = false)
	public int getTaxCode() {
		return this.taxCode;
	}

	public void setTaxCode(int taxCode) {
		this.taxCode = taxCode;
	}

	@Column(name = "tax_desc", nullable = false, length = 65535)
	public String getTaxDesc() {
		return this.taxDesc;
	}

	public void setTaxDesc(String taxDesc) {
		this.taxDesc = taxDesc;
	}

	@Column(name = "tax_pnct", nullable = false, length = 65535)
	public String getTaxPnct() {
		return this.taxPnct;
	}

	public void setTaxPnct(String taxPnct) {
		this.taxPnct = taxPnct;
	}

	@Column(name = "tax_vis_f", nullable = false)
	public byte getTaxVisF() {
		return this.taxVisF;
	}

	public void setTaxVisF(byte taxVisF) {
		this.taxVisF = taxVisF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
