package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LiveChat generated by hbm2java
 */
@Entity
@Table(name = "live_chat", catalog = "starfoodlocal")
public class LiveChat implements java.io.Serializable {

	private Integer id;
	private String chatClientName;
	private String chatId;
	private String visitorId;
	private String chatDate;
	private String chatType;
	private String duration;
	private String startedBy;
	private String visitorName;
	private String visitorEmail;
	private String visitorPhone;
	private String visitorNotes;
	private String sessionCity;
	private String sessionStartDate;
	private String sessionEndDate;
	private String sessionIp;
	private String sessionRegion;
	private String sessionId;
	private String sessionPlatform;
	private String sessionUserAgent;
	private String sessionCountryCode;
	private String sessionCountryName;
	private String sessionBrowser;
	private String visitorMessageCount;
	private String agentMessageCount;
	private String totalMessageCount;
	private String isTriggered;
	private String isMissed;
	private String isUnread;
	private String landingPage;
	private String referral;
	private String tags;
	private String departmentName;
	private String agentNames;
	private String agentIds;
	private String ratingScore;
	private String ratingComment;
	private String maxResponseTime;
	private String avgResponseTime;
	private String firstResponseTime;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public LiveChat() {
	}

	public LiveChat(String crtId, Date crtTs) {
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public LiveChat(String chatClientName, String chatId, String visitorId,
			String chatDate, String chatType, String duration,
			String startedBy, String visitorName, String visitorEmail,
			String visitorPhone, String visitorNotes, String sessionCity,
			String sessionStartDate, String sessionEndDate, String sessionIp,
			String sessionRegion, String sessionId, String sessionPlatform,
			String sessionUserAgent, String sessionCountryCode,
			String sessionCountryName, String sessionBrowser,
			String visitorMessageCount, String agentMessageCount,
			String totalMessageCount, String isTriggered, String isMissed,
			String isUnread, String landingPage, String referral, String tags,
			String departmentName, String agentNames, String agentIds,
			String ratingScore, String ratingComment, String maxResponseTime,
			String avgResponseTime, String firstResponseTime, String crtId,
			Date crtTs, String updId, Date updTs) {
		this.chatClientName = chatClientName;
		this.chatId = chatId;
		this.visitorId = visitorId;
		this.chatDate = chatDate;
		this.chatType = chatType;
		this.duration = duration;
		this.startedBy = startedBy;
		this.visitorName = visitorName;
		this.visitorEmail = visitorEmail;
		this.visitorPhone = visitorPhone;
		this.visitorNotes = visitorNotes;
		this.sessionCity = sessionCity;
		this.sessionStartDate = sessionStartDate;
		this.sessionEndDate = sessionEndDate;
		this.sessionIp = sessionIp;
		this.sessionRegion = sessionRegion;
		this.sessionId = sessionId;
		this.sessionPlatform = sessionPlatform;
		this.sessionUserAgent = sessionUserAgent;
		this.sessionCountryCode = sessionCountryCode;
		this.sessionCountryName = sessionCountryName;
		this.sessionBrowser = sessionBrowser;
		this.visitorMessageCount = visitorMessageCount;
		this.agentMessageCount = agentMessageCount;
		this.totalMessageCount = totalMessageCount;
		this.isTriggered = isTriggered;
		this.isMissed = isMissed;
		this.isUnread = isUnread;
		this.landingPage = landingPage;
		this.referral = referral;
		this.tags = tags;
		this.departmentName = departmentName;
		this.agentNames = agentNames;
		this.agentIds = agentIds;
		this.ratingScore = ratingScore;
		this.ratingComment = ratingComment;
		this.maxResponseTime = maxResponseTime;
		this.avgResponseTime = avgResponseTime;
		this.firstResponseTime = firstResponseTime;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "chat_client_name", length = 500)
	public String getChatClientName() {
		return this.chatClientName;
	}

	public void setChatClientName(String chatClientName) {
		this.chatClientName = chatClientName;
	}

	@Column(name = "chat_id", length = 2000)
	public String getChatId() {
		return this.chatId;
	}

	public void setChatId(String chatId) {
		this.chatId = chatId;
	}

	@Column(name = "visitor_id", length = 2000)
	public String getVisitorId() {
		return this.visitorId;
	}

	public void setVisitorId(String visitorId) {
		this.visitorId = visitorId;
	}

	@Column(name = "chat_date", length = 1000)
	public String getChatDate() {
		return this.chatDate;
	}

	public void setChatDate(String chatDate) {
		this.chatDate = chatDate;
	}

	@Column(name = "chat_type", length = 100)
	public String getChatType() {
		return this.chatType;
	}

	public void setChatType(String chatType) {
		this.chatType = chatType;
	}

	@Column(name = "duration", length = 100)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "started_by", length = 100)
	public String getStartedBy() {
		return this.startedBy;
	}

	public void setStartedBy(String startedBy) {
		this.startedBy = startedBy;
	}

	@Column(name = "visitor_name", length = 1000)
	public String getVisitorName() {
		return this.visitorName;
	}

	public void setVisitorName(String visitorName) {
		this.visitorName = visitorName;
	}

	@Column(name = "visitor_email", length = 2000)
	public String getVisitorEmail() {
		return this.visitorEmail;
	}

	public void setVisitorEmail(String visitorEmail) {
		this.visitorEmail = visitorEmail;
	}

	@Column(name = "visitor_phone", length = 100)
	public String getVisitorPhone() {
		return this.visitorPhone;
	}

	public void setVisitorPhone(String visitorPhone) {
		this.visitorPhone = visitorPhone;
	}

	@Column(name = "visitor_notes", length = 2000)
	public String getVisitorNotes() {
		return this.visitorNotes;
	}

	public void setVisitorNotes(String visitorNotes) {
		this.visitorNotes = visitorNotes;
	}

	@Column(name = "session_city", length = 100)
	public String getSessionCity() {
		return this.sessionCity;
	}

	public void setSessionCity(String sessionCity) {
		this.sessionCity = sessionCity;
	}

	@Column(name = "session_start_date", length = 1000)
	public String getSessionStartDate() {
		return this.sessionStartDate;
	}

	public void setSessionStartDate(String sessionStartDate) {
		this.sessionStartDate = sessionStartDate;
	}

	@Column(name = "session_end_date", length = 1000)
	public String getSessionEndDate() {
		return this.sessionEndDate;
	}

	public void setSessionEndDate(String sessionEndDate) {
		this.sessionEndDate = sessionEndDate;
	}

	@Column(name = "session_ip", length = 100)
	public String getSessionIp() {
		return this.sessionIp;
	}

	public void setSessionIp(String sessionIp) {
		this.sessionIp = sessionIp;
	}

	@Column(name = "session_region", length = 100)
	public String getSessionRegion() {
		return this.sessionRegion;
	}

	public void setSessionRegion(String sessionRegion) {
		this.sessionRegion = sessionRegion;
	}

	@Column(name = "session_id", length = 200)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "session_platform", length = 200)
	public String getSessionPlatform() {
		return this.sessionPlatform;
	}

	public void setSessionPlatform(String sessionPlatform) {
		this.sessionPlatform = sessionPlatform;
	}

	@Column(name = "session_user_agent", length = 200)
	public String getSessionUserAgent() {
		return this.sessionUserAgent;
	}

	public void setSessionUserAgent(String sessionUserAgent) {
		this.sessionUserAgent = sessionUserAgent;
	}

	@Column(name = "session_country_code", length = 200)
	public String getSessionCountryCode() {
		return this.sessionCountryCode;
	}

	public void setSessionCountryCode(String sessionCountryCode) {
		this.sessionCountryCode = sessionCountryCode;
	}

	@Column(name = "session_country_name", length = 200)
	public String getSessionCountryName() {
		return this.sessionCountryName;
	}

	public void setSessionCountryName(String sessionCountryName) {
		this.sessionCountryName = sessionCountryName;
	}

	@Column(name = "session_browser", length = 200)
	public String getSessionBrowser() {
		return this.sessionBrowser;
	}

	public void setSessionBrowser(String sessionBrowser) {
		this.sessionBrowser = sessionBrowser;
	}

	@Column(name = "visitor_message_count", length = 200)
	public String getVisitorMessageCount() {
		return this.visitorMessageCount;
	}

	public void setVisitorMessageCount(String visitorMessageCount) {
		this.visitorMessageCount = visitorMessageCount;
	}

	@Column(name = "agent_message_count", length = 200)
	public String getAgentMessageCount() {
		return this.agentMessageCount;
	}

	public void setAgentMessageCount(String agentMessageCount) {
		this.agentMessageCount = agentMessageCount;
	}

	@Column(name = "total_message_count", length = 200)
	public String getTotalMessageCount() {
		return this.totalMessageCount;
	}

	public void setTotalMessageCount(String totalMessageCount) {
		this.totalMessageCount = totalMessageCount;
	}

	@Column(name = "is_triggered", length = 200)
	public String getIsTriggered() {
		return this.isTriggered;
	}

	public void setIsTriggered(String isTriggered) {
		this.isTriggered = isTriggered;
	}

	@Column(name = "is_missed", length = 200)
	public String getIsMissed() {
		return this.isMissed;
	}

	public void setIsMissed(String isMissed) {
		this.isMissed = isMissed;
	}

	@Column(name = "is_unread", length = 200)
	public String getIsUnread() {
		return this.isUnread;
	}

	public void setIsUnread(String isUnread) {
		this.isUnread = isUnread;
	}

	@Column(name = "landing_page", length = 200)
	public String getLandingPage() {
		return this.landingPage;
	}

	public void setLandingPage(String landingPage) {
		this.landingPage = landingPage;
	}

	@Column(name = "referral", length = 200)
	public String getReferral() {
		return this.referral;
	}

	public void setReferral(String referral) {
		this.referral = referral;
	}

	@Column(name = "tags", length = 200)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Column(name = "department_name", length = 200)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "agent_names", length = 200)
	public String getAgentNames() {
		return this.agentNames;
	}

	public void setAgentNames(String agentNames) {
		this.agentNames = agentNames;
	}

	@Column(name = "agent_ids", length = 200)
	public String getAgentIds() {
		return this.agentIds;
	}

	public void setAgentIds(String agentIds) {
		this.agentIds = agentIds;
	}

	@Column(name = "rating_score", length = 200)
	public String getRatingScore() {
		return this.ratingScore;
	}

	public void setRatingScore(String ratingScore) {
		this.ratingScore = ratingScore;
	}

	@Column(name = "rating_comment", length = 200)
	public String getRatingComment() {
		return this.ratingComment;
	}

	public void setRatingComment(String ratingComment) {
		this.ratingComment = ratingComment;
	}

	@Column(name = "max_response_time", length = 200)
	public String getMaxResponseTime() {
		return this.maxResponseTime;
	}

	public void setMaxResponseTime(String maxResponseTime) {
		this.maxResponseTime = maxResponseTime;
	}

	@Column(name = "avg_response_time", length = 200)
	public String getAvgResponseTime() {
		return this.avgResponseTime;
	}

	public void setAvgResponseTime(String avgResponseTime) {
		this.avgResponseTime = avgResponseTime;
	}

	@Column(name = "first_response_time", length = 200)
	public String getFirstResponseTime() {
		return this.firstResponseTime;
	}

	public void setFirstResponseTime(String firstResponseTime) {
		this.firstResponseTime = firstResponseTime;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
