package com.nibble.starfood.hibernatemodel;

// Generated 24 Oct, 2015 11:35:06 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * MealPlan generated by hbm2java
 */
@Entity
@Table(name = "meal_plan")
public class MealPlan implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private String mealPlanDesc;
	@JsonIgnore
	private int mealPlanF;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String crtTs;
	@JsonIgnore
	private String updTs;
	@JsonIgnore
	private String updId;
	

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "meal_plan_desc", nullable = false, length = 100)
	public String getMealPlanDesc() {
		return this.mealPlanDesc;
	}

	public void setMealPlanDesc(String mealPlanDesc) {
		this.mealPlanDesc = mealPlanDesc;
	}

	@Column(name = "meal_plan_f")
	public int getMealPlanF() {
		return this.mealPlanF;
	}

	public void setMealPlanF(int mealPlanF) {
		this.mealPlanF = mealPlanF;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "crt_ts", length = 45)
	public String getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(String crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_ts", length = 45)
	public String getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(String updTs) {
		this.updTs = updTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}
	
	
}
