package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MealFoodItemRelId generated by hbm2java
 */
@Embeddable
public class MealFoodItemRelId implements java.io.Serializable {

	private int mealId;
	private int foodItemId;

	public MealFoodItemRelId() {
	}

	public MealFoodItemRelId(int mealId, int foodItemId) {
		this.mealId = mealId;
		this.foodItemId = foodItemId;
	}

	@Column(name = "meal_id", nullable = false)
	public int getMealId() {
		return this.mealId;
	}

	public void setMealId(int mealId) {
		this.mealId = mealId;
	}

	@Column(name = "food_item_id", nullable = false)
	public int getFoodItemId() {
		return this.foodItemId;
	}

	public void setFoodItemId(int foodItemId) {
		this.foodItemId = foodItemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MealFoodItemRelId))
			return false;
		MealFoodItemRelId castOther = (MealFoodItemRelId) other;

		return (this.getMealId() == castOther.getMealId())
				&& (this.getFoodItemId() == castOther.getFoodItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMealId();
		result = 37 * result + this.getFoodItemId();
		return result;
	}

}
