package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MealFoodItemRel generated by hbm2java
 */
@Entity
@Table(name = "meal_food_item_rel", catalog = "starfoodlocal")
public class MealFoodItemRel implements java.io.Serializable {

	private MealFoodItemRelId id;

	public MealFoodItemRel() {
	}

	public MealFoodItemRel(MealFoodItemRelId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mealId", column = @Column(name = "meal_id", nullable = false)),
			@AttributeOverride(name = "foodItemId", column = @Column(name = "food_item_id", nullable = false)) })
	public MealFoodItemRelId getId() {
		return this.id;
	}

	public void setId(MealFoodItemRelId id) {
		this.id = id;
	}

}
