package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;





/**
 * MealTime generated by hbm2java
 */
@Entity
@Table(name = "meal_time")
public class MealTime implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String mealTimeDesc;
	private String cutoffTime;
	@JsonIgnore
	private int mealTimeCode;
	@JsonIgnore
	private int mealTimeF;
	@JsonIgnore
	private String slotStrtTime;
	@JsonIgnore
	private String slotEndTime;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;
	@JsonIgnore
	private Set<PkgSizTyp> pkgSizTyp = new HashSet<PkgSizTyp>();
	 @JsonIgnore
	  private Set<CustOrdDet> orders = new HashSet<CustOrdDet>();
	public MealTime() {
	}

	public MealTime(int mealTimeCode, String mealTimeDesc, int mealTimeF,
			Date crtTs, String crtId) {
		this.mealTimeCode = mealTimeCode;
		this.mealTimeDesc = mealTimeDesc;
		this.mealTimeF = mealTimeF;
		this.crtTs = crtTs;
		this.crtId = crtId;
	}

	public MealTime(int mealTimeCode, String mealTimeDesc, int mealTimeF,
			String slotStrtTime, String slotEndTime, String cutoffTime,
			Date crtTs, Date updTs, String crtId, String updId) {
		this.mealTimeCode = mealTimeCode;
		this.mealTimeDesc = mealTimeDesc;
		this.mealTimeF = mealTimeF;
		this.slotStrtTime = slotStrtTime;
		this.slotEndTime = slotEndTime;
		this.cutoffTime = cutoffTime;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "meal_time_code", nullable = false)
	public int getMealTimeCode() {
		return this.mealTimeCode;
	}

	public void setMealTimeCode(int mealTimeCode) {
		this.mealTimeCode = mealTimeCode;
	}

	@Column(name = "meal_time_desc", nullable = false, length = 65535)
	public String getMealTimeDesc() {
		return this.mealTimeDesc;
	}

	public void setMealTimeDesc(String mealTimeDesc) {
		this.mealTimeDesc = mealTimeDesc;
	}

	@Column(name = "meal_time_f", nullable = false)
	public int isMealTimeF() {
		return this.mealTimeF;
	}

	public void setMealTimeF(int mealTimeF) {
		this.mealTimeF = mealTimeF;
	}

	@Column(name = "slot_strt_time", length = 200)
	public String getSlotStrtTime() {
		return this.slotStrtTime;
	}

	public void setSlotStrtTime(String slotStrtTime) {
		this.slotStrtTime = slotStrtTime;
	}

	@Column(name = "slot_end_time", length = 200)
	public String getSlotEndTime() {
		return this.slotEndTime;
	}

	public void setSlotEndTime(String slotEndTime) {
		this.slotEndTime = slotEndTime;
	}

	@Column(name = "cutoff_time", length = 200)
	public String getCutoffTime() {
		return this.cutoffTime;
	}

	public void setCutoffTime(String cutoffTime) {
		this.cutoffTime = cutoffTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mealTime")
	public Set<CustOrdDet> getOrders() {
		return orders;
	}

	public void setOrders(Set<CustOrdDet> orders) {
		this.orders = orders;
	}
	@OneToMany(mappedBy = "mealtime")
	public Set<PkgSizTyp> getPkgSizTyp() {
		return pkgSizTyp;
	}

	public void setPkgSizTyp(Set<PkgSizTyp> pkgSizTyp) {
		this.pkgSizTyp = pkgSizTyp;
	}

	
	

}
