package com.nibble.starfood.hibernatemodel;

// Generated 1 Oct, 2015 4:03:57 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * MenuTyp generated by hbm2java
 */
@Entity
@Table(name = "menu_typ")
public class MenuTyp implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String menuTypDesc;
	private int menuTypF;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;

	@JsonIgnore
	private Set<PkgSizTyp> pkgSizTyp = new HashSet<PkgSizTyp>();
	
	@JsonIgnore
	private Set<CustOrdDet> orders = new HashSet<CustOrdDet>();

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "menu_typ_desc", length = 100)
	public String getMenuTypDesc() {
		return this.menuTypDesc;
	}

	public void setMenuTypDesc(String menuTypDesc) {
		this.menuTypDesc = menuTypDesc;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "menu_typ_f", length = 100)
	public int getMenuTypF() {
		return menuTypF;
	}

	public void setMenuTypF(int menuTypF) {
		this.menuTypF = menuTypF;
	}
	
	 @OneToMany(mappedBy = "menuTyp")
		public Set<PkgSizTyp> getPkgSizTyp() {
			return pkgSizTyp;
		}

		public void setPkgSizTyp(Set<PkgSizTyp> pkgSizTyp) {
			this.pkgSizTyp = pkgSizTyp;
		}
		
		@OneToMany(mappedBy = "menuTyp")
		public Set<CustOrdDet> getOrders() {
			return orders;
		}

		public void setOrders(Set<CustOrdDet> orders) {
			this.orders = orders;
		}

}
