package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mesr generated by hbm2java
 */
@Entity
@Table(name = "mesr", catalog = "starfoodlocal")
public class Mesr implements java.io.Serializable {

	private Integer id;
	private String mesrDesc;
	private Boolean mesrF;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public Mesr() {
	}

	public Mesr(String mesrDesc, Date crtTs, Date updTs) {
		this.mesrDesc = mesrDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public Mesr(String mesrDesc, Boolean mesrF, Date crtTs, Date updTs,
			String crtId, String updId) {
		this.mesrDesc = mesrDesc;
		this.mesrF = mesrF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mesr_desc", nullable = false, length = 1000)
	public String getMesrDesc() {
		return this.mesrDesc;
	}

	public void setMesrDesc(String mesrDesc) {
		this.mesrDesc = mesrDesc;
	}

	@Column(name = "mesr_f")
	public Boolean getMesrF() {
		return this.mesrF;
	}

	public void setMesrF(Boolean mesrF) {
		this.mesrF = mesrF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
