package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdDet generated by hbm2java
 */
@Entity
@Table(name = "ord_det")
public class OrdDet implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer foodCatgTypCode;
	private Integer ordNo;
	private int billdate;
	private int foodItmCode;
	private String foodNoteModif;
	private String foodItmPrc;
	private String kotdelreason;
	private int complF;
	private int foodItmQty;
	private Integer foodItmTstCode;
	private Integer foodItmStCode;
	private Date crtTs;
	private Date upsTs;
	private String crtId;
	private String updId;
	private String orderNoMaster;
	private Integer foodItmReadyQty;
	private int foodItmRemain;
	private String foodItmCodeName;
	private String date;
	private String itemtax;
	private String itemdiscount;
	private byte kitchenStatus;
	private String time;

	public OrdDet() {
	}

	public OrdDet(int billdate, int foodItmCode, String foodItmPrc,
			String kotdelreason, int complF, int foodItmQty, Date crtTs,
			Date upsTs, String crtId, int foodItmRemain,
			String foodItmCodeName, String date, String itemtax,
			String itemdiscount, byte kitchenStatus, String time) {
		this.billdate = billdate;
		this.foodItmCode = foodItmCode;
		this.foodItmPrc = foodItmPrc;
		this.kotdelreason = kotdelreason;
		this.complF = complF;
		this.foodItmQty = foodItmQty;
		this.crtTs = crtTs;
		this.upsTs = upsTs;
		this.crtId = crtId;
		this.foodItmRemain = foodItmRemain;
		this.foodItmCodeName = foodItmCodeName;
		this.date = date;
		this.itemtax = itemtax;
		this.itemdiscount = itemdiscount;
		this.kitchenStatus = kitchenStatus;
		this.time = time;
	}

	public OrdDet(Integer foodCatgTypCode, Integer ordNo, int billdate,
			int foodItmCode, String foodNoteModif, String foodItmPrc,
			String kotdelreason, int complF, int foodItmQty,
			Integer foodItmTstCode, Integer foodItmStCode, Date crtTs,
			Date upsTs, String crtId, String updId, String orderNoMaster,
			Integer foodItmReadyQty, int foodItmRemain, String foodItmCodeName,
			String date, String itemtax, String itemdiscount,
			byte kitchenStatus, String time) {
		this.foodCatgTypCode = foodCatgTypCode;
		this.ordNo = ordNo;
		this.billdate = billdate;
		this.foodItmCode = foodItmCode;
		this.foodNoteModif = foodNoteModif;
		this.foodItmPrc = foodItmPrc;
		this.kotdelreason = kotdelreason;
		this.complF = complF;
		this.foodItmQty = foodItmQty;
		this.foodItmTstCode = foodItmTstCode;
		this.foodItmStCode = foodItmStCode;
		this.crtTs = crtTs;
		this.upsTs = upsTs;
		this.crtId = crtId;
		this.updId = updId;
		this.orderNoMaster = orderNoMaster;
		this.foodItmReadyQty = foodItmReadyQty;
		this.foodItmRemain = foodItmRemain;
		this.foodItmCodeName = foodItmCodeName;
		this.date = date;
		this.itemtax = itemtax;
		this.itemdiscount = itemdiscount;
		this.kitchenStatus = kitchenStatus;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "food_catg_typ_code")
	public Integer getFoodCatgTypCode() {
		return this.foodCatgTypCode;
	}

	public void setFoodCatgTypCode(Integer foodCatgTypCode) {
		this.foodCatgTypCode = foodCatgTypCode;
	}

	@Column(name = "ord_no")
	public Integer getOrdNo() {
		return this.ordNo;
	}

	public void setOrdNo(Integer ordNo) {
		this.ordNo = ordNo;
	}

	@Column(name = "billdate", nullable = false)
	public int getBilldate() {
		return this.billdate;
	}

	public void setBilldate(int billdate) {
		this.billdate = billdate;
	}

	@Column(name = "food_itm_code", nullable = false)
	public int getFoodItmCode() {
		return this.foodItmCode;
	}

	public void setFoodItmCode(int foodItmCode) {
		this.foodItmCode = foodItmCode;
	}

	@Column(name = "food_note_modif", length = 500)
	public String getFoodNoteModif() {
		return this.foodNoteModif;
	}

	public void setFoodNoteModif(String foodNoteModif) {
		this.foodNoteModif = foodNoteModif;
	}

	@Column(name = "food_itm_prc", nullable = false)
	public String getFoodItmPrc() {
		return this.foodItmPrc;
	}

	public void setFoodItmPrc(String foodItmPrc) {
		this.foodItmPrc = foodItmPrc;
	}

	@Column(name = "kotdelreason", nullable = false, length = 200)
	public String getKotdelreason() {
		return this.kotdelreason;
	}

	public void setKotdelreason(String kotdelreason) {
		this.kotdelreason = kotdelreason;
	}

	@Column(name = "compl_f", nullable = false)
	public int getComplF() {
		return this.complF;
	}

	public void setComplF(int complF) {
		this.complF = complF;
	}

	@Column(name = "food_itm_qty", nullable = false)
	public int getFoodItmQty() {
		return this.foodItmQty;
	}

	public void setFoodItmQty(int foodItmQty) {
		this.foodItmQty = foodItmQty;
	}

	@Column(name = "food_itm_tst_code")
	public Integer getFoodItmTstCode() {
		return this.foodItmTstCode;
	}

	public void setFoodItmTstCode(Integer foodItmTstCode) {
		this.foodItmTstCode = foodItmTstCode;
	}

	@Column(name = "food_itm_st_code")
	public Integer getFoodItmStCode() {
		return this.foodItmStCode;
	}

	public void setFoodItmStCode(Integer foodItmStCode) {
		this.foodItmStCode = foodItmStCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ups_ts", nullable = false, length = 19)
	public Date getUpsTs() {
		return this.upsTs;
	}

	public void setUpsTs(Date upsTs) {
		this.upsTs = upsTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "order_no_master")
	public String getOrderNoMaster() {
		return this.orderNoMaster;
	}

	public void setOrderNoMaster(String orderNoMaster) {
		this.orderNoMaster = orderNoMaster;
	}

	@Column(name = "food_itm_ready_qty")
	public Integer getFoodItmReadyQty() {
		return this.foodItmReadyQty;
	}

	public void setFoodItmReadyQty(Integer foodItmReadyQty) {
		this.foodItmReadyQty = foodItmReadyQty;
	}

	@Column(name = "food_itm_remain", nullable = false)
	public int getFoodItmRemain() {
		return this.foodItmRemain;
	}

	public void setFoodItmRemain(int foodItmRemain) {
		this.foodItmRemain = foodItmRemain;
	}

	@Column(name = "food_itm_code_name", nullable = false, length = 45)
	public String getFoodItmCodeName() {
		return this.foodItmCodeName;
	}

	public void setFoodItmCodeName(String foodItmCodeName) {
		this.foodItmCodeName = foodItmCodeName;
	}

	@Column(name = "date", nullable = false, length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "itemtax", nullable = false, length = 45)
	public String getItemtax() {
		return this.itemtax;
	}

	public void setItemtax(String itemtax) {
		this.itemtax = itemtax;
	}

	@Column(name = "itemdiscount", nullable = false, length = 45)
	public String getItemdiscount() {
		return this.itemdiscount;
	}

	public void setItemdiscount(String itemdiscount) {
		this.itemdiscount = itemdiscount;
	}

	@Column(name = "kitchen_status", nullable = false)
	public byte getKitchenStatus() {
		return this.kitchenStatus;
	}

	public void setKitchenStatus(byte kitchenStatus) {
		this.kitchenStatus = kitchenStatus;
	}

	@Column(name = "time", nullable = false, length = 200)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
