package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name = "order_item")
public class OrderItem implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private int poId;
	private int produtctId;
	private Integer orderFrequencyId;
	private int priceId;
	private Date cancelDate;
	private int osStatusId;

	public OrderItem() {
	}

	public OrderItem(int id, int poId, int produtctId, int priceId,
			int osStatusId) {
		this.id = id;
		this.poId = poId;
		this.produtctId = produtctId;
		this.priceId = priceId;
		this.osStatusId = osStatusId;
	}

	public OrderItem(int id, String name, int poId, int produtctId,
			Integer orderFrequencyId, int priceId, Date cancelDate,
			int osStatusId) {
		this.id = id;
		this.name = name;
		this.poId = poId;
		this.produtctId = produtctId;
		this.orderFrequencyId = orderFrequencyId;
		this.priceId = priceId;
		this.cancelDate = cancelDate;
		this.osStatusId = osStatusId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "po_id", nullable = false)
	public int getPoId() {
		return this.poId;
	}

	public void setPoId(int poId) {
		this.poId = poId;
	}

	@Column(name = "produtct_id", nullable = false)
	public int getProdutctId() {
		return this.produtctId;
	}

	public void setProdutctId(int produtctId) {
		this.produtctId = produtctId;
	}

	@Column(name = "order_frequency_id")
	public Integer getOrderFrequencyId() {
		return this.orderFrequencyId;
	}

	public void setOrderFrequencyId(Integer orderFrequencyId) {
		this.orderFrequencyId = orderFrequencyId;
	}

	@Column(name = "price_id", nullable = false)
	public int getPriceId() {
		return this.priceId;
	}

	public void setPriceId(int priceId) {
		this.priceId = priceId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cancel_date", length = 10)
	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}

	@Column(name = "os_status_id", nullable = false)
	public int getOsStatusId() {
		return this.osStatusId;
	}

	public void setOsStatusId(int osStatusId) {
		this.osStatusId = osStatusId;
	}

}
