package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ordrs generated by hbm2java
 */
@Entity
@Table(name = "ordrs")
public class Ordrs implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer ordNo;
	private Integer paxCount;
	private String voidbillComment;
	private String waiterId;
	private String kotNo;
	private String tblCode;
	private String tablNumber;
	private String gstName;
	private Date ordTime;
	private int ordStCode;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;
	private String orderTotalPrice;
	private String orderNoMaster;
	private String mobNo;
	private String gstAddress;
	private String gstEmail;
	private String date;
	private String time;
	private String noOfGst;
	private String ordTyp;

	public Ordrs() {
	}

	public Ordrs(String voidbillComment, String tablNumber, String gstName,
			Date ordTime, int ordStCode, Date crtTs, Date updTs,
			String orderTotalPrice, String mobNo, String date) {
		this.voidbillComment = voidbillComment;
		this.tablNumber = tablNumber;
		this.gstName = gstName;
		this.ordTime = ordTime;
		this.ordStCode = ordStCode;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.orderTotalPrice = orderTotalPrice;
		this.mobNo = mobNo;
		this.date = date;
	}

	public Ordrs(Integer ordNo, Integer paxCount, String voidbillComment,
			String waiterId, String kotNo, String tblCode, String tablNumber,
			String gstName, Date ordTime, int ordStCode, Date crtTs,
			Date updTs, String crtId, String updId, String orderTotalPrice,
			String orderNoMaster, String mobNo, String gstAddress,
			String gstEmail, String date, String time, String noOfGst,
			String ordTyp) {
		this.ordNo = ordNo;
		this.paxCount = paxCount;
		this.voidbillComment = voidbillComment;
		this.waiterId = waiterId;
		this.kotNo = kotNo;
		this.tblCode = tblCode;
		this.tablNumber = tablNumber;
		this.gstName = gstName;
		this.ordTime = ordTime;
		this.ordStCode = ordStCode;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
		this.orderTotalPrice = orderTotalPrice;
		this.orderNoMaster = orderNoMaster;
		this.mobNo = mobNo;
		this.gstAddress = gstAddress;
		this.gstEmail = gstEmail;
		this.date = date;
		this.time = time;
		this.noOfGst = noOfGst;
		this.ordTyp = ordTyp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ord_no")
	public Integer getOrdNo() {
		return this.ordNo;
	}

	public void setOrdNo(Integer ordNo) {
		this.ordNo = ordNo;
	}

	@Column(name = "pax_count")
	public Integer getPaxCount() {
		return this.paxCount;
	}

	public void setPaxCount(Integer paxCount) {
		this.paxCount = paxCount;
	}

	@Column(name = "voidbill_comment", nullable = false, length = 500)
	public String getVoidbillComment() {
		return this.voidbillComment;
	}

	public void setVoidbillComment(String voidbillComment) {
		this.voidbillComment = voidbillComment;
	}

	@Column(name = "waiter_id", length = 100)
	public String getWaiterId() {
		return this.waiterId;
	}

	public void setWaiterId(String waiterId) {
		this.waiterId = waiterId;
	}

	@Column(name = "kot_no", length = 2000)
	public String getKotNo() {
		return this.kotNo;
	}

	public void setKotNo(String kotNo) {
		this.kotNo = kotNo;
	}

	@Column(name = "tbl_code", length = 30)
	public String getTblCode() {
		return this.tblCode;
	}

	public void setTblCode(String tblCode) {
		this.tblCode = tblCode;
	}

	@Column(name = "tabl_number", nullable = false, length = 100)
	public String getTablNumber() {
		return this.tablNumber;
	}

	public void setTablNumber(String tablNumber) {
		this.tablNumber = tablNumber;
	}

	@Column(name = "gst_name", nullable = false, length = 100)
	public String getGstName() {
		return this.gstName;
	}

	public void setGstName(String gstName) {
		this.gstName = gstName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ord_time", nullable = false, length = 19)
	public Date getOrdTime() {
		return this.ordTime;
	}

	public void setOrdTime(Date ordTime) {
		this.ordTime = ordTime;
	}

	@Column(name = "ord_st_code", nullable = false)
	public int getOrdStCode() {
		return this.ordStCode;
	}

	public void setOrdStCode(int ordStCode) {
		this.ordStCode = ordStCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "order_total_price", nullable = false, length = 100)
	public String getOrderTotalPrice() {
		return this.orderTotalPrice;
	}

	public void setOrderTotalPrice(String orderTotalPrice) {
		this.orderTotalPrice = orderTotalPrice;
	}

	@Column(name = "order_no_master")
	public String getOrderNoMaster() {
		return this.orderNoMaster;
	}

	public void setOrderNoMaster(String orderNoMaster) {
		this.orderNoMaster = orderNoMaster;
	}

	@Column(name = "mob_no", nullable = false, length = 100)
	public String getMobNo() {
		return this.mobNo;
	}

	public void setMobNo(String mobNo) {
		this.mobNo = mobNo;
	}

	@Column(name = "gst_address", length = 500)
	public String getGstAddress() {
		return this.gstAddress;
	}

	public void setGstAddress(String gstAddress) {
		this.gstAddress = gstAddress;
	}

	@Column(name = "gst_email", length = 145)
	public String getGstEmail() {
		return this.gstEmail;
	}

	public void setGstEmail(String gstEmail) {
		this.gstEmail = gstEmail;
	}

	@Column(name = "date", nullable = false, length = 100)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "time", length = 100)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "no_of_gst", length = 100)
	public String getNoOfGst() {
		return this.noOfGst;
	}

	public void setNoOfGst(String noOfGst) {
		this.noOfGst = noOfGst;
	}

	@Column(name = "ord_typ", length = 100)
	public String getOrdTyp() {
		return this.ordTyp;
	}

	public void setOrdTyp(String ordTyp) {
		this.ordTyp = ordTyp;
	}

}
