package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * PayMod generated by hbm2java
 */
@Entity
@Table(name = "pay_mod")
public class PayMod implements java.io.Serializable {

	private Integer id;
	private String payTyp;
	@JsonIgnore
	private int payModF;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;

	public PayMod() {
	}

	public PayMod(int payModF, Date crtTs, String crtId, String updId) {
		this.payModF = payModF;
		this.crtTs = crtTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	public PayMod(String payTyp, int payModF, Date crtTs, Date updTs,
			String crtId, String updId) {
		this.payTyp = payTyp;
		this.payModF = payModF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pay_typ", length = 100)
	public String getPayTyp() {
		return this.payTyp;
	}

	public void setPayTyp(String payTyp) {
		this.payTyp = payTyp;
	}

	@Column(name = "pay_mod_f", nullable = false)
	public int isPayModF() {
		return this.payModF;
	}

	public void setPayModF(int payModF) {
		this.payModF = payModF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", nullable = false, length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
