package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * PaymentGatewayDet generated by hbm2java
 */
@Entity
@Table(name = "payment_gateway_det")
public class PaymentGatewayDet implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int paymentGatewayId;
	private int paymentDatewayF;
	private String merchantKey;
	private String merchantSalt;
	private String SUrl;
	private String FUrl;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;

	public PaymentGatewayDet() {
	}

	public PaymentGatewayDet(int paymentGatewayId, String merchantKey,
			String merchantSalt, String SUrl, String FUrl, Date crtTs,
			Date updTs) {
		this.paymentGatewayId = paymentGatewayId;
		this.merchantKey = merchantKey;
		this.merchantSalt = merchantSalt;
		this.SUrl = SUrl;
		this.FUrl = FUrl;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public PaymentGatewayDet(int paymentGatewayId, String merchantKey,
			String merchantSalt, String SUrl, String FUrl, Date crtTs,
			Date updTs, String crtId, String updId) {
		this.paymentGatewayId = paymentGatewayId;
		this.merchantKey = merchantKey;
		this.merchantSalt = merchantSalt;
		this.SUrl = SUrl;
		this.FUrl = FUrl;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "payment_gateway_id", nullable = false)
	public int getPaymentGatewayId() {
		return this.paymentGatewayId;
	}

	public void setPaymentGatewayId(int paymentGatewayId) {
		this.paymentGatewayId = paymentGatewayId;
	}

	@Column(name = "merchant_key", nullable = false, length = 200)
	public String getMerchantKey() {
		return this.merchantKey;
	}

	public void setMerchantKey(String merchantKey) {
		this.merchantKey = merchantKey;
	}

	@Column(name = "merchant_salt", nullable = false, length = 200)
	public String getMerchantSalt() {
		return this.merchantSalt;
	}

	public void setMerchantSalt(String merchantSalt) {
		this.merchantSalt = merchantSalt;
	}

	@Column(name = "s_url", nullable = false, length = 500)
	public String getSUrl() {
		return this.SUrl;
	}

	public void setSUrl(String SUrl) {
		this.SUrl = SUrl;
	}

	@Column(name = "f_url", nullable = false, length = 500)
	public String getFUrl() {
		return this.FUrl;
	}

	public void setFUrl(String FUrl) {
		this.FUrl = FUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}
	@Column(name = "payment_gateway_f", nullable = false)
	public int getPaymentDatewayF() {
		return paymentDatewayF;
	}

	public void setPaymentDatewayF(int paymentDatewayF) {
		this.paymentDatewayF = paymentDatewayF;
	}

}
