package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Pincode generated by hbm2java
 */
@Entity
@Table(name = "pincode")
public class Pincode implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String pincodeDesc;
	@JsonIgnore
	private Integer areaId;
	@JsonIgnore
	private int pincodeVisF;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;
	@JsonIgnore
	private Set<Area> areas = new HashSet<Area>(0);
	
	@JsonIgnore
	private Set<Address> address = new HashSet<Address>(0);
	
	public Pincode() {
	}

	public Pincode(String pincodeDesc, int pincodeVisF, Date crtTs,
			Date updTs, String crtId) {
		this.pincodeDesc = pincodeDesc;
		this.pincodeVisF = pincodeVisF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
	}

	public Pincode(String pincodeDesc, Integer areaId, int pincodeVisF,
			Date crtTs, Date updTs, String crtId, String updId) {
		this.pincodeDesc = pincodeDesc;
		this.areaId = areaId;
		this.pincodeVisF = pincodeVisF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pincode_desc", nullable = false, length = 200)
	public String getPincodeDesc() {
		return this.pincodeDesc;
	}

	public void setPincodeDesc(String pincodeDesc) {
		this.pincodeDesc = pincodeDesc;
	}

	@Column(name = "area_id")
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@Column(name = "pincode_vis_f", nullable = false)
	public int isPincodeVisF() {
		return this.pincodeVisF;
	}

	public void setPincodeVisF(int pincodeVisF) {
		this.pincodeVisF = pincodeVisF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}
	/*@OneToMany(fetch=FetchType.LAZY,mappedBy="pincode")
	public Set<Area> getAreas() {
		return areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}*/
	@OneToMany(mappedBy="pincode")
	public Set<Address> getAddress() {
		return address;
	}

	public void setAddress(Set<Address> address) {
		this.address = address;
	}
}
