package com.nibble.starfood.hibernatemodel;

// Generated 22 Sep, 2015 1:55:20 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * PkgConfigRelt generated by hbm2java
 */
@Entity
@Table(name = "pkg_config_relt")
public class PkgConfigRelt implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	@JsonIgnore
	private Integer id;
	private int pkgConfigReltF;
	//private PkgSizTyp packag;
	//private int pkgSizTypId;
	private PkgSizTyp packagSize;
	private PkgFoodItm items;
	@JsonIgnore
	private int foodtypeid;
	@JsonIgnore
	private int pkgFoodCatgId;
	@JsonIgnore
	private String menuDate;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;
	@JsonIgnore
	private int mealTime;
	@JsonIgnore
	private int monthNo;



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/*@Column(name = "pkg_siz_typ_id", nullable = false)
	public int getPkgSizTypId() {
		return this.pkgSizTypId;
	}

	public void setPkgSizTypId(int pkgSizTypId) {
		this.pkgSizTypId = pkgSizTypId;
	}*/

	/*@Column(name = "food_typ_id", nullable = false)
	public int getPkgFoodItmId() {
		return this.foodtypeid;
	}

	public void setPkgFoodItmId(int foodtypeid) {
		this.foodtypeid = foodtypeid;
	}*/

	@Column(name = "pkg_food_catg_id", nullable = false)
	public int getPkgFoodCatgId() {
		return this.pkgFoodCatgId;
	}

	public void setPkgFoodCatgId(int pkgFoodCatgId) {
		this.pkgFoodCatgId = pkgFoodCatgId;
	}

	@Column(name = "menu_date", nullable = false, length = 200)
	public String getMenuDate() {
		return this.menuDate;
	}

	public void setMenuDate(String menuDate) {
		this.menuDate = menuDate;
	}
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "pkg_food_itm_id", nullable = false)
	public PkgFoodItm getItems() {
		return items;
	}

	public void setItems(PkgFoodItm items) {
		this.items = items;
	}
	@Column(name = "meal_time_id", nullable = false, length = 200)
	public int getMealTime() {
		return mealTime;
	}

	public void setMealTime(int mealTime) {
		this.mealTime = mealTime;
	}
	@Column(name = "month_no", nullable = false, length = 200)
	public int getMonthNo() {
		return monthNo;
	}

	public void setMonthNo(int monthNo) {
		this.monthNo = monthNo;
	}
	@Column(name = "food_typ_id", nullable = false)
	public int getFoodtypeid() {
		return foodtypeid;
	}

	public void setFoodtypeid(int foodtypeid) {
		this.foodtypeid = foodtypeid;
	}
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "pkg_siz_typ_id", nullable = false)
	public PkgSizTyp getPackagSize() {
		return packagSize;
	}

	public void setPackagSize(PkgSizTyp packagSize) {
		this.packagSize = packagSize;
	}
	@Column(name = "pkg_config_relt_f", nullable = false)
	public int getPkgConfigReltF() {
		return pkgConfigReltF;
	}

	public void setPkgConfigReltF(int pkgConfigReltF) {
		this.pkgConfigReltF = pkgConfigReltF;
	}
	/*@Column(name = "pkg_siz_typ_id", nullable = false)
	public int getPkgSizTypId() {
		return pkgSizTypId;
	}

	public void setPkgSizTypId(int pkgSizTypId) {
		this.pkgSizTypId = pkgSizTypId;
	}*/

	/*public PkgSizTyp getPackag() {
		return packag;
	}

	public void setPackag(PkgSizTyp packag) {
		this.packag = packag;
	}*/
	
	

}
