package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PkgFoodMenuRelt generated by hbm2java
 */
@Entity
@Table(name = "pkg_food_menu_relt")
public class PkgFoodMenuRelt implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int foodCatgId;
	private int foodItmId;
	private Integer foodItmQty;
	private Integer date;
	private Integer weekDayId;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public PkgFoodMenuRelt() {
	}

	public PkgFoodMenuRelt(int foodCatgId, int foodItmId, String crtId,
			Date crtTs) {
		this.foodCatgId = foodCatgId;
		this.foodItmId = foodItmId;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public PkgFoodMenuRelt(int foodCatgId, int foodItmId, Integer foodItmQty,
			Integer date, Integer weekDayId, String crtId, Date crtTs,
			String updId, Date updTs) {
		this.foodCatgId = foodCatgId;
		this.foodItmId = foodItmId;
		this.foodItmQty = foodItmQty;
		this.date = date;
		this.weekDayId = weekDayId;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "food_catg_id", nullable = false)
	public int getFoodCatgId() {
		return this.foodCatgId;
	}

	public void setFoodCatgId(int foodCatgId) {
		this.foodCatgId = foodCatgId;
	}

	@Column(name = "food_itm_id", nullable = false)
	public int getFoodItmId() {
		return this.foodItmId;
	}

	public void setFoodItmId(int foodItmId) {
		this.foodItmId = foodItmId;
	}

	@Column(name = "food_itm_qty")
	public Integer getFoodItmQty() {
		return this.foodItmQty;
	}

	public void setFoodItmQty(Integer foodItmQty) {
		this.foodItmQty = foodItmQty;
	}

	@Column(name = "date")
	public Integer getDate() {
		return this.date;
	}

	public void setDate(Integer date) {
		this.date = date;
	}

	@Column(name = "week_day_id")
	public Integer getWeekDayId() {
		return this.weekDayId;
	}

	public void setWeekDayId(Integer weekDayId) {
		this.weekDayId = weekDayId;
	}

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
