package com.nibble.starfood.hibernatemodel;
// Generated 1 Oct, two015 four:03:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * PkgPrice generated by hbm2java
 */
@Entity
@Table(name="pkg_price")
public class PkgPrice  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	  @JsonIgnore
	 private Integer id;
     private float oneDayPrice;
     private float oneWeekPrice;
     private float oneMonthPrice;
   
     private float threedaysPrice;
     
    
     private float twoMonthPrice;
     @JsonIgnore
     private float threeMonthPrice;
     @JsonIgnore
     private float fourMonthPrice;
     @JsonIgnore
     private float fiveMonthPrice;
     @JsonIgnore
     private float sixMonthPrice;
     @JsonIgnore
     private float oneWeekSixDayPrice;
  
     private float oneWeekFiveDayPrice;
     @JsonIgnore
     private Date crtTs;
     @JsonIgnore
     private String updTs;
     @JsonIgnore
     private String crtId;
     @JsonIgnore
     private String updId;
     
  

     @JsonIgnore
 	private Set<PkgSizTyp> pkgSizTyp = new HashSet<PkgSizTyp>();
   
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

    
    @Column(name="one_day_price", nullable=false, precision=10)
    public float getoneDayPrice() {
        return this.oneDayPrice;
    }
    
    public void setoneDayPrice(float oneDayPrice) {
        this.oneDayPrice = oneDayPrice;
    }

    
    @Column(name="one_week_price", nullable=false, precision=10)
    public float getoneWeekPrice() {
        return this.oneWeekPrice;
    }
    
    public void setoneWeekPrice(float oneWeekPrice) {
        this.oneWeekPrice = oneWeekPrice;
    }

    
    @Column(name="one_month_price", nullable=false, precision=10)
    public float getoneMonthPrice() {
        return this.oneMonthPrice;
    }
    
    public void setoneMonthPrice(float oneMonthPrice) {
        this.oneMonthPrice = oneMonthPrice;
    }

    
    @Column(name="two_month_price", nullable=false, precision=10)
    public float gettwoMonthPrice() {
        return this.twoMonthPrice;
    }
    
    public void settwoMonthPrice(float twoMonthPrice) {
        this.twoMonthPrice = twoMonthPrice;
    }

    
    @Column(name="three_month_price", nullable=false, precision=10)
    public float getthreeMonthPrice() {
        return this.threeMonthPrice;
    }
    
    public void setthreeMonthPrice(float threeMonthPrice) {
        this.threeMonthPrice = threeMonthPrice;
    }
  
    
    
    @Column(name="three_days_price", nullable=false, precision=10)
	public float getThreedaysPrice() {
		return threedaysPrice;
	}

	public void setThreedaysPrice(float threedaysPrice) {
		this.threedaysPrice = threedaysPrice;
	}

	@Column(name="four_month_price", nullable=false, precision=10)
    public float getfourMonthPrice() {
        return this.fourMonthPrice;
    }
    
    public void setfourMonthPrice(float fourMonthPrice) {
        this.fourMonthPrice = fourMonthPrice;
    }

    
    @Column(name="five_month_price", nullable=false, precision=10)
    public float getfiveMonthPrice() {
        return this.fiveMonthPrice;
    }
    
    public void setfiveMonthPrice(float fiveMonthPrice) {
        this.fiveMonthPrice = fiveMonthPrice;
    }

    
    @Column(name="six_month_price", nullable=false, precision=10)
    public float getsixMonthPrice() {
        return this.sixMonthPrice;
    }
    
    public void setsixMonthPrice(float sixMonthPrice) {
        this.sixMonthPrice = sixMonthPrice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="crt_ts", nullable=false, length=19)
    public Date getCrtTs() {
        return this.crtTs;
    }
    
    public void setCrtTs(Date crtTs) {
        this.crtTs = crtTs;
    }

    
    @Column(name="upd_ts", length=500)
    public String getUpdTs() {
        return this.updTs;
    }
    
    public void setUpdTs(String updTs) {
        this.updTs = updTs;
    }

    
    @Column(name="crt_id", length=100)
    public String getCrtId() {
        return this.crtId;
    }
    
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    
    @Column(name="upd_id", length=100)
    public String getUpdId() {
        return this.updId;
    }
    
    public void setUpdId(String updId) {
        this.updId = updId;
    }

    @OneToMany(mappedBy = "pkgPrice")
	public Set<PkgSizTyp> getPkgSizTyp() {
		return pkgSizTyp;
	}

	public void setPkgSizTyp(Set<PkgSizTyp> pkgSizTyp) {
		this.pkgSizTyp = pkgSizTyp;
	}
	 @Column(name="one_week_6day", nullable=false, precision=10)
	public float getOneWeekSixDayPrice() {
		return oneWeekSixDayPrice;
	}

	public void setOneWeekSixDayPrice(float oneWeekSixDayPrice) {
		this.oneWeekSixDayPrice = oneWeekSixDayPrice;
	}
	@Column(name="one_week_5day", nullable=false, precision=10)
	public float getOneWeekFiveDayPrice() {
		return oneWeekFiveDayPrice;
	}

	public void setOneWeekFiveDayPrice(float oneWeekFiveDayPrice) {
		this.oneWeekFiveDayPrice = oneWeekFiveDayPrice;
	}




}


