package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PkgSizTypFoodRelt generated by hbm2java
 */
@Entity
@Table(name = "pkg_siz_typ_food_relt")
public class PkgSizTypFoodRelt implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int pkgSizTypId;
	private int foodCatgId;
	private int foodCatgQty;
	private Boolean foodCatgF;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public PkgSizTypFoodRelt() {
	}

	public PkgSizTypFoodRelt(int pkgSizTypId, int foodCatgId, int foodCatgQty,
			String crtId, Date crtTs) {
		this.pkgSizTypId = pkgSizTypId;
		this.foodCatgId = foodCatgId;
		this.foodCatgQty = foodCatgQty;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public PkgSizTypFoodRelt(int pkgSizTypId, int foodCatgId, int foodCatgQty,
			Boolean foodCatgF, String crtId, Date crtTs, String updId,
			Date updTs) {
		this.pkgSizTypId = pkgSizTypId;
		this.foodCatgId = foodCatgId;
		this.foodCatgQty = foodCatgQty;
		this.foodCatgF = foodCatgF;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pkg_siz_typ_id", nullable = false)
	public int getPkgSizTypId() {
		return this.pkgSizTypId;
	}

	public void setPkgSizTypId(int pkgSizTypId) {
		this.pkgSizTypId = pkgSizTypId;
	}

	@Column(name = "food_catg_id", nullable = false)
	public int getFoodCatgId() {
		return this.foodCatgId;
	}

	public void setFoodCatgId(int foodCatgId) {
		this.foodCatgId = foodCatgId;
	}

	@Column(name = "food_catg_qty", nullable = false)
	public int getFoodCatgQty() {
		return this.foodCatgQty;
	}

	public void setFoodCatgQty(int foodCatgQty) {
		this.foodCatgQty = foodCatgQty;
	}

	@Column(name = "food_catg_f")
	public Boolean getFoodCatgF() {
		return this.foodCatgF;
	}

	public void setFoodCatgF(Boolean foodCatgF) {
		this.foodCatgF = foodCatgF;
	}

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
