package com.nibble.starfood.hibernatemodel;

// Generated 1 Oct, 2015 4:03:57 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * PkgSizTyp generated by hbm2java
 */
@Entity
@Table(name = "pkg_siz_typ")
public class PkgSizTyp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	//private Integer mealTimeId;
	private String pkgSizTypDesc;
	private String pkgImg;
	/*private String pkgName;
	public String getPkgName() {
		return pkgName;
	}

	public void setPkgName(String pkgName) {
		this.pkgName = pkgName;
	}*/

	private int pkgStockCount;
	private int pkgFoodCatgId;
	private Integer mealCnt;
	private PkgPrice pkgPrice;
	private String onlinePayChrg;
	private Tax tax;
	private DelvChrg delvChrg;
	private PkgDur pkgDuration;
    private WeekTyp weekTyp; 
	private int cityId;
	private int pkgSizTypF;
	private MealTime mealtime;
	private MealTyp mealType;
	private FoodTyp foodtyp;
	private MenuTyp menuTyp;
	//private int mealTypId;
	//private int weekDurId;
	//private int foodTypId;
	//private int pkgDurId;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private String updId;
	@JsonIgnore
	private Date updTs;

	@JsonIgnore
	private Set<CustOrdDet> orders = new HashSet<CustOrdDet>();

	@JsonIgnore
	private Set<PkgConfigRelt> packagSize = new HashSet<PkgConfigRelt>();



	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/*@Column(name = "meal_time_id", nullable = false)
	public Integer getMealTimeId() {
		return this.mealTimeId;
	}

	public void setMealTimeId(Integer mealTimeId) {
		this.mealTimeId = mealTimeId;
	}*/

	@Column(name = "pkg_siz_typ_desc", nullable = false, length = 200)
	public String getPkgSizTypDesc() {
		return this.pkgSizTypDesc;
	}

	public void setPkgSizTypDesc(String pkgSizTypDesc) {
		this.pkgSizTypDesc = pkgSizTypDesc;
	}

	@Column(name = "pkg_siz_typ_f", nullable = false)
	public int isPkgSizTypF() {
		return this.pkgSizTypF;
	}

	public void setPkgSizTypF(int pkgSizTypF) {
		this.pkgSizTypF = pkgSizTypF;
	}

	@Column(name = "pkg_img", length = 500)
	public String getPkgImg() {
		return this.pkgImg;
	}

	public void setPkgImg(String pkgImg) {
		this.pkgImg = pkgImg;
	}

	@Column(name = "pkg_stock_count", nullable = false, length = 200)
	public int getPkgStockCount() {
		return this.pkgStockCount;
	}

	public void setPkgStockCount(int pkgStockCount) {
		this.pkgStockCount = pkgStockCount;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "menu_typ_id", nullable = false)
	public MenuTyp getMenuTyp() {
		return menuTyp;
	}

	public void setMenuTyp(MenuTyp menuTyp) {
		this.menuTyp = menuTyp;
	}
	//@Column(name = "menu_typ_id", nullable = false)
	/*public int getMenuTypId() {
		return this.menuTypId;
	}

	public void setMenuTypId(int menuTypId) {
		this.menuTypId = menuTypId;
	}*/

	@Column(name = "pkg_food_catg_id", nullable = false)
	public int getPkgFoodCatgId() {
		return this.pkgFoodCatgId;
	}

	public void setPkgFoodCatgId(int pkgFoodCatgId) {
		this.pkgFoodCatgId = pkgFoodCatgId;
	}

	@Column(name = "city_id", nullable = false)
	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

	/*@Column(name = "meal_typ_id", nullable = false)
	public int getMealTypId() {
		return this.mealTypId;
	}

	public void setMealTypId(int mealTypId) {
		this.mealTypId = mealTypId;
	}*/

	/*@Column(name = "week_dur_id", nullable = false)
	public int getWeekDurId() {
		return this.weekDurId;
	}

	public void setWeekDurId(int weekDurId) {
		this.weekDurId = weekDurId;
	}*/

	/*@Column(name = "food_typ_id", nullable = false)
	public int getFoodTypId() {
		return this.foodTypId;
	}

	public void setFoodTypId(int foodTypId) {
		this.foodTypId = foodTypId;
	}
*//*
	@Column(name = "pkg_dur_id", nullable = false)
	public int getPkgDurId() {
		return this.pkgDurId;
	}

	public void setPkgDurId(int pkgDurId) {
		this.pkgDurId = pkgDurId;
	}
*/
	@Column(name = "meal_cnt")
	public Integer getMealCnt() {
		return this.mealCnt;
	}

	public void setMealCnt(Integer mealCnt) {
		this.mealCnt = mealCnt;
	}

	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pkg_price_id", nullable = false)
	public PkgPrice getPkgPrice() {
		return pkgPrice;
	}

	public void setPkgPrice(PkgPrice pkgPrice) {
		this.pkgPrice = pkgPrice;
	}

	@Column(name = "online_pay_chrg", length = 200)
	public String getOnlinePayChrg() {
		return this.onlinePayChrg;
	}

	public void setOnlinePayChrg(String onlinePayChrg) {
		this.onlinePayChrg = onlinePayChrg;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "delv_chrg_id", nullable = false)
	public DelvChrg getDelvChrg() {
		return delvChrg;
	}

	public void setDelvChrg(DelvChrg delvChrg) {
		this.delvChrg = delvChrg;
	}

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", nullable = false, length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "meal_time_id", nullable = false)
	public MealTime getMealtime() {
		return mealtime;
	}

	public void setMealtime(MealTime mealtime) {
		this.mealtime = mealtime;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "food_typ_id", nullable = false)
	public FoodTyp getFoodtyp() {
		return foodtyp;
	}

	public void setFoodtyp(FoodTyp foodtyp) {
		this.foodtyp = foodtyp;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pkg_dur_id", nullable = false)
	public PkgDur getPkgDuration() {
		return pkgDuration;
	}

	public void setPkgDuration(PkgDur pkgDuration) {
		this.pkgDuration = pkgDuration;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "week_dur_id", nullable = false)
	public WeekTyp getWeekTyp() {
		return weekTyp;
	}

	public void setWeekTyp(WeekTyp weekTyp) {
		this.weekTyp = weekTyp;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tax_id", nullable = false)
	public Tax getTax() {
		return tax;
	}

	public void setTax(Tax tax) {
		this.tax = tax;
	}
	/*@OneToMany(mappedBy = "pkgSize")
	public Set<CustOrdDet> getOrders() {
		return orders;
	}

	public void setOrders(Set<CustOrdDet> orders) {
		this.orders = orders;
	}*/
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "meal_typ_id", nullable = false)
	public MealTyp getMealType() {
		return mealType;
	}

	public void setMealType(MealTyp mealType) {
		this.mealType = mealType;
	}

	
	
	@OneToMany(mappedBy = "packagSize")
	public Set<PkgConfigRelt> getPackagSize() {
		return packagSize;
	}

	public void setPackagSize(Set<PkgConfigRelt> packagSize) {
		this.packagSize = packagSize;
	}
	
	@OneToMany(mappedBy = "pkgSize")
	public Set<CustOrdDet> getOrders() {
		return orders;
	}

	public void setOrders(Set<CustOrdDet> orders) {
		this.orders = orders;
	}

	
	
}
