package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PkgSoldOutCount generated by hbm2java
 */
@Entity
@Table(name = "pkg_sold_out_count")
public class PkgSoldOutCount implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String date;
	private int pkgSizTypId;
	private int soldCount;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public PkgSoldOutCount() {
	}

	public PkgSoldOutCount(String date, int pkgSizTypId, int soldCount,
			Date crtTs) {
		this.date = date;
		this.pkgSizTypId = pkgSizTypId;
		this.soldCount = soldCount;
		this.crtTs = crtTs;
	}

	public PkgSoldOutCount(String date, int pkgSizTypId, int soldCount,
			Date crtTs, Date updTs, String crtId, String updId) {
		this.date = date;
		this.pkgSizTypId = pkgSizTypId;
		this.soldCount = soldCount;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "date", nullable = false, length = 200)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "pkg_siz_typ_id", nullable = false)
	public int getPkgSizTypId() {
		return this.pkgSizTypId;
	}

	public void setPkgSizTypId(int pkgSizTypId) {
		this.pkgSizTypId = pkgSizTypId;
	}

	@Column(name = "sold_count", nullable = false)
	public int getSoldCount() {
		return this.soldCount;
	}

	public void setSoldCount(int soldCount) {
		this.soldCount = soldCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
