package com.nibble.starfood.hibernatemodel;

// Generated 22 Sep, 2015 1:55:20 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanType generated by hbm2java
 */
@Entity
@Table(name = "plan_type")
public class PlanType implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String planTypeDesc;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public PlanType() {
	}

	public PlanType(String planTypeDesc) {
		this.planTypeDesc = planTypeDesc;
	}

	public PlanType(String planTypeDesc, Date crtTs, Date updTs, String crtId,
			String updId) {
		this.planTypeDesc = planTypeDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "plan_type_desc", nullable = false, length = 45)
	public String getPlanTypeDesc() {
		return this.planTypeDesc;
	}

	public void setPlanTypeDesc(String planTypeDesc) {
		this.planTypeDesc = planTypeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
