package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductPrice generated by hbm2java
 */
@Entity
@Table(name = "product_price", catalog = "starfoodlocal")
public class ProductPrice implements java.io.Serializable {

	private int id;
	private Long price;

	public ProductPrice() {
	}

	public ProductPrice(int id) {
		this.id = id;
	}

	public ProductPrice(int id, Long price) {
		this.id = id;
		this.price = price;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

}
