package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdProdItemJoinId generated by hbm2java
 */
@Embeddable
public class ProdProdItemJoinId implements java.io.Serializable {

	private int productId;
	private int productItemId;

	public ProdProdItemJoinId() {
	}

	public ProdProdItemJoinId(int productId, int productItemId) {
		this.productId = productId;
		this.productItemId = productItemId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "product_item_id", nullable = false)
	public int getProductItemId() {
		return this.productItemId;
	}

	public void setProductItemId(int productItemId) {
		this.productItemId = productItemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdProdItemJoinId))
			return false;
		ProdProdItemJoinId castOther = (ProdProdItemJoinId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getProductItemId() == castOther.getProductItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getProductItemId();
		return result;
	}

}
