package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseOrder generated by hbm2java
 */
@Entity
@Table(name = "purchase_order")
public class PurchaseOrder implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private Long orderPrice;
	private Integer orderStatusId;
	private Integer customerId;
	private Date orderDate;

	public PurchaseOrder() {
	}

	public PurchaseOrder(int id) {
		this.id = id;
	}

	public PurchaseOrder(int id, Long orderPrice, Integer orderStatusId,
			Integer customerId, Date orderDate) {
		this.id = id;
		this.orderPrice = orderPrice;
		this.orderStatusId = orderStatusId;
		this.customerId = customerId;
		this.orderDate = orderDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "order_price", precision = 10, scale = 0)
	public Long getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(Long orderPrice) {
		this.orderPrice = orderPrice;
	}

	@Column(name = "order_status_id")
	public Integer getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Integer orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

}
