package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RawMatVend generated by hbm2java
 */
@Entity
@Table(name = "raw_mat_vend")
public class RawMatVend implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer rawMatItmId;
	private String rawMatVendDesc;
	private String rawMatVendCntcNo;
	private String rawMatVendEmail;
	private String rawMatVendAddr;
	private Boolean rawMatVendF;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public RawMatVend() {
	}

	public RawMatVend(String rawMatVendDesc, Date crtTs, Date updTs) {
		this.rawMatVendDesc = rawMatVendDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public RawMatVend(Integer rawMatItmId, String rawMatVendDesc,
			String rawMatVendCntcNo, String rawMatVendEmail,
			String rawMatVendAddr, Boolean rawMatVendF, Date crtTs, Date updTs,
			String crtId, String updId) {
		this.rawMatItmId = rawMatItmId;
		this.rawMatVendDesc = rawMatVendDesc;
		this.rawMatVendCntcNo = rawMatVendCntcNo;
		this.rawMatVendEmail = rawMatVendEmail;
		this.rawMatVendAddr = rawMatVendAddr;
		this.rawMatVendF = rawMatVendF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "raw_mat_itm_id")
	public Integer getRawMatItmId() {
		return this.rawMatItmId;
	}

	public void setRawMatItmId(Integer rawMatItmId) {
		this.rawMatItmId = rawMatItmId;
	}

	@Column(name = "raw_mat_vend_desc", nullable = false, length = 1000)
	public String getRawMatVendDesc() {
		return this.rawMatVendDesc;
	}

	public void setRawMatVendDesc(String rawMatVendDesc) {
		this.rawMatVendDesc = rawMatVendDesc;
	}

	@Column(name = "raw_mat_vend_cntc_no", length = 1000)
	public String getRawMatVendCntcNo() {
		return this.rawMatVendCntcNo;
	}

	public void setRawMatVendCntcNo(String rawMatVendCntcNo) {
		this.rawMatVendCntcNo = rawMatVendCntcNo;
	}

	@Column(name = "raw_mat_vend_email", length = 1000)
	public String getRawMatVendEmail() {
		return this.rawMatVendEmail;
	}

	public void setRawMatVendEmail(String rawMatVendEmail) {
		this.rawMatVendEmail = rawMatVendEmail;
	}

	@Column(name = "raw_mat_vend_addr", length = 2000)
	public String getRawMatVendAddr() {
		return this.rawMatVendAddr;
	}

	public void setRawMatVendAddr(String rawMatVendAddr) {
		this.rawMatVendAddr = rawMatVendAddr;
	}

	@Column(name = "raw_mat_vend_f")
	public Boolean getRawMatVendF() {
		return this.rawMatVendF;
	}

	public void setRawMatVendF(Boolean rawMatVendF) {
		this.rawMatVendF = rawMatVendF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
