package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RawMatBrnd generated by hbm2java
 */
@Entity
@Table(name = "raw_mat_brnd")
public class RawMatBrnd implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int rawMatItmId;
	private String rawMatBrndDesc;
	private Boolean rawMatBrndF;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public RawMatBrnd() {
	}

	public RawMatBrnd(int rawMatItmId, String rawMatBrndDesc, Date crtTs,
			Date updTs) {
		this.rawMatItmId = rawMatItmId;
		this.rawMatBrndDesc = rawMatBrndDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public RawMatBrnd(int rawMatItmId, String rawMatBrndDesc,
			Boolean rawMatBrndF, Date crtTs, Date updTs, String crtId,
			String updId) {
		this.rawMatItmId = rawMatItmId;
		this.rawMatBrndDesc = rawMatBrndDesc;
		this.rawMatBrndF = rawMatBrndF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "raw_mat_itm_id", nullable = false)
	public int getRawMatItmId() {
		return this.rawMatItmId;
	}

	public void setRawMatItmId(int rawMatItmId) {
		this.rawMatItmId = rawMatItmId;
	}

	@Column(name = "raw_mat_brnd_desc", nullable = false, length = 1000)
	public String getRawMatBrndDesc() {
		return this.rawMatBrndDesc;
	}

	public void setRawMatBrndDesc(String rawMatBrndDesc) {
		this.rawMatBrndDesc = rawMatBrndDesc;
	}

	@Column(name = "raw_mat_brnd_f")
	public Boolean getRawMatBrndF() {
		return this.rawMatBrndF;
	}

	public void setRawMatBrndF(Boolean rawMatBrndF) {
		this.rawMatBrndF = rawMatBrndF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
