package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RawMatItm generated by hbm2java
 */
@Entity
@Table(name = "raw_mat_itm")
public class RawMatItm implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String rawMatItmDesc;
	private int rawMatCatgId;
	private int rawMatSubCatgId;
	private String rawMatPurDt;
	private String rawMatExpDt;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public RawMatItm() {
	}

	public RawMatItm(String rawMatItmDesc, int rawMatCatgId,
			int rawMatSubCatgId, Date crtTs, Date updTs) {
		this.rawMatItmDesc = rawMatItmDesc;
		this.rawMatCatgId = rawMatCatgId;
		this.rawMatSubCatgId = rawMatSubCatgId;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public RawMatItm(String rawMatItmDesc, int rawMatCatgId,
			int rawMatSubCatgId, String rawMatPurDt, String rawMatExpDt,
			Date crtTs, Date updTs, String crtId, String updId) {
		this.rawMatItmDesc = rawMatItmDesc;
		this.rawMatCatgId = rawMatCatgId;
		this.rawMatSubCatgId = rawMatSubCatgId;
		this.rawMatPurDt = rawMatPurDt;
		this.rawMatExpDt = rawMatExpDt;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "raw_mat_itm_desc", nullable = false, length = 1000)
	public String getRawMatItmDesc() {
		return this.rawMatItmDesc;
	}

	public void setRawMatItmDesc(String rawMatItmDesc) {
		this.rawMatItmDesc = rawMatItmDesc;
	}

	@Column(name = "raw_mat_catg_id", nullable = false)
	public int getRawMatCatgId() {
		return this.rawMatCatgId;
	}

	public void setRawMatCatgId(int rawMatCatgId) {
		this.rawMatCatgId = rawMatCatgId;
	}

	@Column(name = "raw_mat_sub_catg_id", nullable = false)
	public int getRawMatSubCatgId() {
		return this.rawMatSubCatgId;
	}

	public void setRawMatSubCatgId(int rawMatSubCatgId) {
		this.rawMatSubCatgId = rawMatSubCatgId;
	}

	@Column(name = "raw_mat_pur_dt", length = 200)
	public String getRawMatPurDt() {
		return this.rawMatPurDt;
	}

	public void setRawMatPurDt(String rawMatPurDt) {
		this.rawMatPurDt = rawMatPurDt;
	}

	@Column(name = "raw_mat_exp_dt", length = 200)
	public String getRawMatExpDt() {
		return this.rawMatExpDt;
	}

	public void setRawMatExpDt(String rawMatExpDt) {
		this.rawMatExpDt = rawMatExpDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
