package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RawMatItmAvl generated by hbm2java
 */
@Entity
@Table(name = "raw_mat_itm_avl")
public class RawMatItmAvl implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int rawMatItmId;
	private Integer rawMatAvlQty;
	private int mesrId;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;

	public RawMatItmAvl() {
	}

	public RawMatItmAvl(int rawMatItmId, int mesrId, Date crtTs, Date updTs) {
		this.rawMatItmId = rawMatItmId;
		this.mesrId = mesrId;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public RawMatItmAvl(int rawMatItmId, Integer rawMatAvlQty, int mesrId,
			Date crtTs, Date updTs, String crtId, String updId) {
		this.rawMatItmId = rawMatItmId;
		this.rawMatAvlQty = rawMatAvlQty;
		this.mesrId = mesrId;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "raw_mat_itm_id", nullable = false)
	public int getRawMatItmId() {
		return this.rawMatItmId;
	}

	public void setRawMatItmId(int rawMatItmId) {
		this.rawMatItmId = rawMatItmId;
	}

	@Column(name = "raw_mat_avl_qty")
	public Integer getRawMatAvlQty() {
		return this.rawMatAvlQty;
	}

	public void setRawMatAvlQty(Integer rawMatAvlQty) {
		this.rawMatAvlQty = rawMatAvlQty;
	}

	@Column(name = "mesr_id", nullable = false)
	public int getMesrId() {
		return this.mesrId;
	}

	public void setMesrId(int mesrId) {
		this.mesrId = mesrId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
