package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefrlTyp generated by hbm2java
 */
@Entity
@Table(name = "refrl_typ")
public class RefrlTyp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String refrlTypDesc;
	private String crtId;
	private Date crtTs;
	private Date updTs;
	private String updId;

	public RefrlTyp() {
	}

	public RefrlTyp(String refrlTypDesc, String crtId, Date crtTs) {
		this.refrlTypDesc = refrlTypDesc;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public RefrlTyp(String refrlTypDesc, String crtId, Date crtTs, Date updTs,
			String updId) {
		this.refrlTypDesc = refrlTypDesc;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "refrl_typ_desc", nullable = false, length = 200)
	public String getRefrlTypDesc() {
		return this.refrlTypDesc;
	}

	public void setRefrlTypDesc(String refrlTypDesc) {
		this.refrlTypDesc = refrlTypDesc;
	}

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "upd_id", length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

}
