package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequestCall generated by hbm2java
 */
@Entity
@Table(name = "request_call", catalog = "spiceboxcoupon")
public class RequestCall implements java.io.Serializable {

	private Integer id;
	private int requestId;
	private String tblNo;
	private byte flag;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public RequestCall() {
	}

	public RequestCall(int requestId, String tblNo, byte flag, Date crtTs,
			Date updTs) {
		this.requestId = requestId;
		this.tblNo = tblNo;
		this.flag = flag;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public RequestCall(int requestId, String tblNo, byte flag, String crtId,
			Date crtTs, String updId, Date updTs) {
		this.requestId = requestId;
		this.tblNo = tblNo;
		this.flag = flag;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "request_id", nullable = false)
	public int getRequestId() {
		return this.requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	@Column(name = "tbl_no", nullable = false, length = 45)
	public String getTblNo() {
		return this.tblNo;
	}

	public void setTblNo(String tblNo) {
		this.tblNo = tblNo;
	}

	@Column(name = "flag", nullable = false)
	public byte getFlag() {
		return this.flag;
	}

	public void setFlag(byte flag) {
		this.flag = flag;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
