package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RunRawMat generated by hbm2java
 */
@Entity
@Table(name = "run_raw_mat", catalog = "starfoodlocal")
public class RunRawMat implements java.io.Serializable {

	private Integer id;
	private int rawMatItmId;
	private String rawMatQty;
	private int mesrId;
	private Boolean rawMatF;
	private String curDate;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public RunRawMat() {
	}

	public RunRawMat(int rawMatItmId, String rawMatQty, int mesrId, Date crtTs,
			Date updTs) {
		this.rawMatItmId = rawMatItmId;
		this.rawMatQty = rawMatQty;
		this.mesrId = mesrId;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public RunRawMat(int rawMatItmId, String rawMatQty, int mesrId,
			Boolean rawMatF, String curDate, String crtId, Date crtTs,
			String updId, Date updTs) {
		this.rawMatItmId = rawMatItmId;
		this.rawMatQty = rawMatQty;
		this.mesrId = mesrId;
		this.rawMatF = rawMatF;
		this.curDate = curDate;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "raw_mat_itm_id", nullable = false)
	public int getRawMatItmId() {
		return this.rawMatItmId;
	}

	public void setRawMatItmId(int rawMatItmId) {
		this.rawMatItmId = rawMatItmId;
	}

	@Column(name = "raw_mat_qty", nullable = false, length = 45)
	public String getRawMatQty() {
		return this.rawMatQty;
	}

	public void setRawMatQty(String rawMatQty) {
		this.rawMatQty = rawMatQty;
	}

	@Column(name = "mesr_id", nullable = false)
	public int getMesrId() {
		return this.mesrId;
	}

	public void setMesrId(int mesrId) {
		this.mesrId = mesrId;
	}

	@Column(name = "raw_mat_f")
	public Boolean getRawMatF() {
		return this.rawMatF;
	}

	public void setRawMatF(Boolean rawMatF) {
		this.rawMatF = rawMatF;
	}

	@Column(name = "curDate", length = 100)
	public String getCurDate() {
		return this.curDate;
	}

	public void setCurDate(String curDate) {
		this.curDate = curDate;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
