package com.nibble.starfood.hibernatemodel;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustFdbkRelt generated by hbm2java
 */
@Entity
@Table(name = "cust_cmt")
public class SaveComment  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

		private Integer id;
		private int custDetId;
		private String fdbkCmnts;

		

		@Id
		@GeneratedValue(strategy = IDENTITY)
		@Column(name = "id", unique = true, nullable = false)
		public Integer getId() {
			return this.id;
		}

		public void setId(Integer id) {
			this.id = id;
		}

		@Column(name = "cust_det_id", nullable = false)
		public int getCustDetId() {
			return this.custDetId;
		}

		public void setCustDetId(int custDetId) {
			this.custDetId = custDetId;
		}

	
		@Column(name = "fdbk_cmnts", nullable = false, length = 200)
		public String getFdbkCmnts() {
			return this.fdbkCmnts;
		}

		public void setFdbkCmnts(String fdbkCmnts) {
			this.fdbkCmnts = fdbkCmnts;
		}

	

	


}
