package com.nibble.starfood.hibernatemodel;

// Generated 22 Sep, 2015 1:55:20 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * SingleDayRelt generated by hbm2java
 */
@Entity
@Table(name = "single_day_relt")
public class SingleDayRelt implements java.io.Serializable {
	

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String menuDate;
	private int pkgFoodCatgId;
	private PkgFoodItm pkgFoodItm;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;
	

	public SingleDayRelt() {
	}

	


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "menu_date", nullable = false, length = 45)
	public String getMenuDate() {
		return this.menuDate;
	}

	public void setMenuDate(String menuDate) {
		this.menuDate = menuDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	/*@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pkg_food_catg_id", nullable = false)
	public PkgFoodCatg getPkgFoodCatg() {
		return pkgFoodCatg;
	}

	public void setPkgFoodCatg(PkgFoodCatg pkgFoodCatg) {
		this.pkgFoodCatg = pkgFoodCatg;
	}*/

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pkg_food_itm_id", nullable = false)
	public PkgFoodItm getPkgFoodItm() {
		return pkgFoodItm;
	}

	public void setPkgFoodItm(PkgFoodItm pkgFoodItm) {
		this.pkgFoodItm = pkgFoodItm;
	}
	
	@Column(name = "pkg_food_catg_id", nullable = false)
	public int getPkgFoodCatgId() {
		return pkgFoodCatgId;
	}

	public void setPkgFoodCatgId(int pkgFoodCatgId) {
		this.pkgFoodCatgId = pkgFoodCatgId;
	}

}
