package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmsData generated by hbm2java
 */
@Entity
@Table(name = "sms_data", catalog = "starfoodlocal")
public class SmsData implements java.io.Serializable {

	private Integer id;
	private String smsClientName;
	private String smsId;
	private String direction;
	private String type;
	private String fromNo;
	private String toNo;
	private String bodyTxt;
	private String status;
	private String time;
	private String price;
	private String fromCrcle;
	private String toCrcle;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public SmsData() {
	}

	public SmsData(String crtId, Date crtTs) {
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public SmsData(String smsClientName, String smsId, String direction,
			String type, String fromNo, String toNo, String bodyTxt,
			String status, String time, String price, String fromCrcle,
			String toCrcle, String crtId, Date crtTs, String updId, Date updTs) {
		this.smsClientName = smsClientName;
		this.smsId = smsId;
		this.direction = direction;
		this.type = type;
		this.fromNo = fromNo;
		this.toNo = toNo;
		this.bodyTxt = bodyTxt;
		this.status = status;
		this.time = time;
		this.price = price;
		this.fromCrcle = fromCrcle;
		this.toCrcle = toCrcle;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sms_client_name", length = 500)
	public String getSmsClientName() {
		return this.smsClientName;
	}

	public void setSmsClientName(String smsClientName) {
		this.smsClientName = smsClientName;
	}

	@Column(name = "sms_id", length = 1000)
	public String getSmsId() {
		return this.smsId;
	}

	public void setSmsId(String smsId) {
		this.smsId = smsId;
	}

	@Column(name = "direction", length = 500)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "type", length = 500)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "from_no", length = 100)
	public String getFromNo() {
		return this.fromNo;
	}

	public void setFromNo(String fromNo) {
		this.fromNo = fromNo;
	}

	@Column(name = "to_no", length = 100)
	public String getToNo() {
		return this.toNo;
	}

	public void setToNo(String toNo) {
		this.toNo = toNo;
	}

	@Column(name = "body_txt", length = 100)
	public String getBodyTxt() {
		return this.bodyTxt;
	}

	public void setBodyTxt(String bodyTxt) {
		this.bodyTxt = bodyTxt;
	}

	@Column(name = "status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "time", length = 100)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "price", length = 100)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "from_crcle", length = 10)
	public String getFromCrcle() {
		return this.fromCrcle;
	}

	public void setFromCrcle(String fromCrcle) {
		this.fromCrcle = fromCrcle;
	}

	@Column(name = "to_crcle", length = 10)
	public String getToCrcle() {
		return this.toCrcle;
	}

	public void setToCrcle(String toCrcle) {
		this.toCrcle = toCrcle;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
