package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmsTmplt generated by hbm2java
 */
@Entity
@Table(name = "sms_tmplt", catalog = "starfoodlocal")
public class SmsTmplt implements java.io.Serializable {

	private Integer id;
	private Integer smsTypId;
	private String smsTypDesc;
	private String smsBody;
	private String exotelTmpltDesc;
	private boolean exotelTmpltF;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public SmsTmplt() {
	}

	public SmsTmplt(String smsTypDesc, String smsBody, String exotelTmpltDesc,
			boolean exotelTmpltF, String crtId, Date crtTs) {
		this.smsTypDesc = smsTypDesc;
		this.smsBody = smsBody;
		this.exotelTmpltDesc = exotelTmpltDesc;
		this.exotelTmpltF = exotelTmpltF;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public SmsTmplt(Integer smsTypId, String smsTypDesc, String smsBody,
			String exotelTmpltDesc, boolean exotelTmpltF, String crtId,
			Date crtTs, String updId, Date updTs) {
		this.smsTypId = smsTypId;
		this.smsTypDesc = smsTypDesc;
		this.smsBody = smsBody;
		this.exotelTmpltDesc = exotelTmpltDesc;
		this.exotelTmpltF = exotelTmpltF;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sms_typ_id")
	public Integer getSmsTypId() {
		return this.smsTypId;
	}

	public void setSmsTypId(Integer smsTypId) {
		this.smsTypId = smsTypId;
	}

	@Column(name = "sms_typ_desc", nullable = false, length = 200)
	public String getSmsTypDesc() {
		return this.smsTypDesc;
	}

	public void setSmsTypDesc(String smsTypDesc) {
		this.smsTypDesc = smsTypDesc;
	}

	@Column(name = "sms_body", nullable = false, length = 200)
	public String getSmsBody() {
		return this.smsBody;
	}

	public void setSmsBody(String smsBody) {
		this.smsBody = smsBody;
	}

	@Column(name = "exotel_tmplt_desc", nullable = false, length = 200)
	public String getExotelTmpltDesc() {
		return this.exotelTmpltDesc;
	}

	public void setExotelTmpltDesc(String exotelTmpltDesc) {
		this.exotelTmpltDesc = exotelTmpltDesc;
	}

	@Column(name = "exotel_tmplt_f", nullable = false)
	public boolean isExotelTmpltF() {
		return this.exotelTmpltF;
	}

	public void setExotelTmpltF(boolean exotelTmpltF) {
		this.exotelTmpltF = exotelTmpltF;
	}

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
