package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", catalog = "starfoodlocal")
public class Staff implements java.io.Serializable {

	private Integer id;
	private String stfId;
	private String stfName;
	private int stfRole;
	private String stfUsrName;
	private String stfUsrPwd;
	private boolean stfVisF;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;
	private Integer deviceId;

	public Staff() {
	}

	public Staff(String stfId, String stfName, int stfRole, boolean stfVisF,
			Date crtTs, Date updTs, String crtId) {
		this.stfId = stfId;
		this.stfName = stfName;
		this.stfRole = stfRole;
		this.stfVisF = stfVisF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
	}

	public Staff(String stfId, String stfName, int stfRole, String stfUsrName,
			String stfUsrPwd, boolean stfVisF, Date crtTs, Date updTs,
			String crtId, String updId, Integer deviceId) {
		this.stfId = stfId;
		this.stfName = stfName;
		this.stfRole = stfRole;
		this.stfUsrName = stfUsrName;
		this.stfUsrPwd = stfUsrPwd;
		this.stfVisF = stfVisF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
		this.deviceId = deviceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "stf_id", nullable = false)
	public String getStfId() {
		return this.stfId;
	}

	public void setStfId(String stfId) {
		this.stfId = stfId;
	}

	@Column(name = "stf_name", nullable = false, length = 65535)
	public String getStfName() {
		return this.stfName;
	}

	public void setStfName(String stfName) {
		this.stfName = stfName;
	}

	@Column(name = "stf_role", nullable = false)
	public int getStfRole() {
		return this.stfRole;
	}

	public void setStfRole(int stfRole) {
		this.stfRole = stfRole;
	}

	@Column(name = "stf_usr_name", length = 100)
	public String getStfUsrName() {
		return this.stfUsrName;
	}

	public void setStfUsrName(String stfUsrName) {
		this.stfUsrName = stfUsrName;
	}

	@Column(name = "stf_usr_pwd", length = 100)
	public String getStfUsrPwd() {
		return this.stfUsrPwd;
	}

	public void setStfUsrPwd(String stfUsrPwd) {
		this.stfUsrPwd = stfUsrPwd;
	}

	@Column(name = "stf_vis_f", nullable = false)
	public boolean isStfVisF() {
		return this.stfVisF;
	}

	public void setStfVisF(boolean stfVisF) {
		this.stfVisF = stfVisF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "device_id")
	public Integer getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

}
