package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "state")
public class State implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String stateDesc;
	@JsonIgnore
	private int cntryId;
	@JsonIgnore
	private int stateF;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private String updId;
	@JsonIgnore
	private Set<Area> areas = new HashSet<Area>(0);
	@JsonIgnore
	private Set<Address> address = new HashSet<Address>(0);
	public State() {
	}

	public State(String stateDesc, int cntryId, int stateF, Date crtTs,
			Date updTs, String crtId, String updId) {
		this.stateDesc = stateDesc;
		this.cntryId = cntryId;
		this.stateF = stateF;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "state_desc", nullable = false, length = 100)
	public String getStateDesc() {
		return this.stateDesc;
	}

	public void setStateDesc(String stateDesc) {
		this.stateDesc = stateDesc;
	}

	@Column(name = "cntry_id", nullable = false)
	public int getCntryId() {
		return this.cntryId;
	}

	public void setCntryId(int cntryId) {
		this.cntryId = cntryId;
	}

	@Column(name = "state_f", nullable = false)
	public int isStateF() {
		return this.stateF;
	}

	public void setStateF(int stateF) {
		this.stateF = stateF;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", nullable = false, length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}
	@OneToMany(fetch=FetchType.LAZY,mappedBy="state")
	public Set<Area> getAreas() {
		return areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}
	@OneToMany(fetch=FetchType.LAZY,mappedBy="state")
	public Set<Address> getAddress() {
		return address;
	}

	public void setAddress(Set<Address> address) {
		this.address = address;
	}

}
