package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StfDevTblRelt generated by hbm2java
 */
@Entity
@Table(name = "stf_dev_tbl_relt", catalog = "starfoodlocal")
public class StfDevTblRelt implements java.io.Serializable {

	private Integer id;
	private Integer stfId;
	private int devId;
	private int tblId;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public StfDevTblRelt() {
	}

	public StfDevTblRelt(int devId, int tblId, Date crtTs, Date updTs) {
		this.devId = devId;
		this.tblId = tblId;
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public StfDevTblRelt(Integer stfId, int devId, int tblId, String crtId,
			Date crtTs, String updId, Date updTs) {
		this.stfId = stfId;
		this.devId = devId;
		this.tblId = tblId;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "stf_id")
	public Integer getStfId() {
		return this.stfId;
	}

	public void setStfId(Integer stfId) {
		this.stfId = stfId;
	}

	@Column(name = "dev_id", nullable = false)
	public int getDevId() {
		return this.devId;
	}

	public void setDevId(int devId) {
		this.devId = devId;
	}

	@Column(name = "tbl_id", nullable = false)
	public int getTblId() {
		return this.tblId;
	}

	public void setTblId(int tblId) {
		this.tblId = tblId;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
