package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tabl generated by hbm2java
 */
@Entity
@Table(name = "tabl", catalog = "spiceboxcoupon")
public class Tabl implements java.io.Serializable {

	private Integer id;
	private int tblName;
	private String tableSeater;
	private String tblDesc;
	private String tblImg;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;
	private byte tblVisF;
	private Byte deviceId;

	public Tabl() {
	}

	public Tabl(int tblName, String tblDesc, Date crtTs, Date updTs,
			String crtId, byte tblVisF) {
		this.tblName = tblName;
		this.tblDesc = tblDesc;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.tblVisF = tblVisF;
	}

	public Tabl(int tblName, String tableSeater, String tblDesc, String tblImg,
			Date crtTs, Date updTs, String crtId, String updId, byte tblVisF,
			Byte deviceId) {
		this.tblName = tblName;
		this.tableSeater = tableSeater;
		this.tblDesc = tblDesc;
		this.tblImg = tblImg;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
		this.tblVisF = tblVisF;
		this.deviceId = deviceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tbl_name", nullable = false)
	public int getTblName() {
		return this.tblName;
	}

	public void setTblName(int tblName) {
		this.tblName = tblName;
	}

	@Column(name = "table_seater", length = 200)
	public String getTableSeater() {
		return this.tableSeater;
	}

	public void setTableSeater(String tableSeater) {
		this.tableSeater = tableSeater;
	}

	@Column(name = "tbl_desc", nullable = false, length = 65535)
	public String getTblDesc() {
		return this.tblDesc;
	}

	public void setTblDesc(String tblDesc) {
		this.tblDesc = tblDesc;
	}

	@Column(name = "tbl_img", length = 200)
	public String getTblImg() {
		return this.tblImg;
	}

	public void setTblImg(String tblImg) {
		this.tblImg = tblImg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", nullable = false, length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "tbl_vis_f", nullable = false)
	public byte getTblVisF() {
		return this.tblVisF;
	}

	public void setTblVisF(byte tblVisF) {
		this.tblVisF = tblVisF;
	}

	@Column(name = "device_id")
	public Byte getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Byte deviceId) {
		this.deviceId = deviceId;
	}

}
