package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TableNumber generated by hbm2java
 */
@Entity
@Table(name = "table_number", catalog = "spiceboxcoupon")
public class TableNumber implements java.io.Serializable {

	private Integer id;
	private String tabletModel;
	private String uniqueCode;
	private String tabletName;
	private String personName;
	private Integer tableNoCode;

	public TableNumber() {
	}

	public TableNumber(String uniqueCode) {
		this.uniqueCode = uniqueCode;
	}

	public TableNumber(String tabletModel, String uniqueCode,
			String tabletName, String personName, Integer tableNoCode) {
		this.tabletModel = tabletModel;
		this.uniqueCode = uniqueCode;
		this.tabletName = tabletName;
		this.personName = personName;
		this.tableNoCode = tableNoCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tablet_model", length = 65535)
	public String getTabletModel() {
		return this.tabletModel;
	}

	public void setTabletModel(String tabletModel) {
		this.tabletModel = tabletModel;
	}

	@Column(name = "unique_code", nullable = false)
	public String getUniqueCode() {
		return this.uniqueCode;
	}

	public void setUniqueCode(String uniqueCode) {
		this.uniqueCode = uniqueCode;
	}

	@Column(name = "tablet_name")
	public String getTabletName() {
		return this.tabletName;
	}

	public void setTabletName(String tabletName) {
		this.tabletName = tabletName;
	}

	@Column(name = "person_name")
	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	@Column(name = "table_no_code")
	public Integer getTableNoCode() {
		return this.tableNoCode;
	}

	public void setTableNoCode(Integer tableNoCode) {
		this.tableNoCode = tableNoCode;
	}

}
