package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TiktDet generated by hbm2java
 */
@Entity
@Table(name = "tikt_det", catalog = "starfoodlocal")
public class TiktDet implements java.io.Serializable {

	private Integer id;
	private Integer tiktTypeId;
	private String custCntcNo;
	private String custEmailId;
	private String tiktDesc;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public TiktDet() {
	}

	public TiktDet(String custCntcNo, Date crtTs) {
		this.custCntcNo = custCntcNo;
		this.crtTs = crtTs;
	}

	public TiktDet(Integer tiktTypeId, String custCntcNo, String custEmailId,
			String tiktDesc, String crtId, Date crtTs, String updId, Date updTs) {
		this.tiktTypeId = tiktTypeId;
		this.custCntcNo = custCntcNo;
		this.custEmailId = custEmailId;
		this.tiktDesc = tiktDesc;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tikt_type_id")
	public Integer getTiktTypeId() {
		return this.tiktTypeId;
	}

	public void setTiktTypeId(Integer tiktTypeId) {
		this.tiktTypeId = tiktTypeId;
	}

	@Column(name = "cust_cntc_no", nullable = false, length = 100)
	public String getCustCntcNo() {
		return this.custCntcNo;
	}

	public void setCustCntcNo(String custCntcNo) {
		this.custCntcNo = custCntcNo;
	}

	@Column(name = "cust_email_id", length = 45)
	public String getCustEmailId() {
		return this.custEmailId;
	}

	public void setCustEmailId(String custEmailId) {
		this.custEmailId = custEmailId;
	}

	@Column(name = "tikt_desc", length = 2000)
	public String getTiktDesc() {
		return this.tiktDesc;
	}

	public void setTiktDesc(String tiktDesc) {
		this.tiktDesc = tiktDesc;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
