package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TiktType generated by hbm2java
 */
@Entity
@Table(name = "tikt_type", catalog = "starfoodlocal")
public class TiktType implements java.io.Serializable {

	private int id;
	private String tiktTydDesc;
	private Integer tiktTypeF;
	private String cktId;
	private Date cktTs;
	private String updId;
	private Date updTs;

	public TiktType() {
	}

	public TiktType(int id, Date cktTs) {
		this.id = id;
		this.cktTs = cktTs;
	}

	public TiktType(int id, String tiktTydDesc, Integer tiktTypeF,
			String cktId, Date cktTs, String updId, Date updTs) {
		this.id = id;
		this.tiktTydDesc = tiktTydDesc;
		this.tiktTypeF = tiktTypeF;
		this.cktId = cktId;
		this.cktTs = cktTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tikt_tyd_desc", length = 100)
	public String getTiktTydDesc() {
		return this.tiktTydDesc;
	}

	public void setTiktTydDesc(String tiktTydDesc) {
		this.tiktTydDesc = tiktTydDesc;
	}

	@Column(name = "tikt_type_f")
	public Integer getTiktTypeF() {
		return this.tiktTypeF;
	}

	public void setTiktTypeF(Integer tiktTypeF) {
		this.tiktTypeF = tiktTypeF;
	}

	@Column(name = "ckt_id", length = 45)
	public String getCktId() {
		return this.cktId;
	}

	public void setCktId(String cktId) {
		this.cktId = cktId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ckt_ts", nullable = false, length = 19)
	public Date getCktTs() {
		return this.cktTs;
	}

	public void setCktTs(Date cktTs) {
		this.cktTs = cktTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
