package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAskedQus generated by hbm2java
 */
@Entity
@Table(name = "user_asked_qus", catalog = "starfoodlocal")
public class UserAskedQus implements java.io.Serializable {

	private Integer id;
	private String qus;

	public UserAskedQus() {
	}

	public UserAskedQus(String qus) {
		this.qus = qus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "qus", nullable = false, length = 65535)
	public String getQus() {
		return this.qus;
	}

	public void setQus(String qus) {
		this.qus = qus;
	}

}
