package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserAskedAns generated by hbm2java
 */
@Entity
@Table(name = "user_asked_ans", catalog = "starfoodlocal")
public class UserAskedAns implements java.io.Serializable {

	private Integer id;
	private String userAnsDesc;
	private String que1;
	private String que2;
	private String que3;
	private String que4;
	private String que5;
	private String comments;
	private String userName;
	private String userEmail;
	private String userContact;
	private String date;
	private String tableNo;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public UserAskedAns() {
	}

	public UserAskedAns(Date crtTs, Date updTs) {
		this.crtTs = crtTs;
		this.updTs = updTs;
	}

	public UserAskedAns(String userAnsDesc, String que1, String que2,
			String que3, String que4, String que5, String comments,
			String userName, String userEmail, String userContact, String date,
			String tableNo, String crtId, Date crtTs, String updId, Date updTs) {
		this.userAnsDesc = userAnsDesc;
		this.que1 = que1;
		this.que2 = que2;
		this.que3 = que3;
		this.que4 = que4;
		this.que5 = que5;
		this.comments = comments;
		this.userName = userName;
		this.userEmail = userEmail;
		this.userContact = userContact;
		this.date = date;
		this.tableNo = tableNo;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_ans_desc", length = 700)
	public String getUserAnsDesc() {
		return this.userAnsDesc;
	}

	public void setUserAnsDesc(String userAnsDesc) {
		this.userAnsDesc = userAnsDesc;
	}

	@Column(name = "que1", length = 45)
	public String getQue1() {
		return this.que1;
	}

	public void setQue1(String que1) {
		this.que1 = que1;
	}

	@Column(name = "que2", length = 45)
	public String getQue2() {
		return this.que2;
	}

	public void setQue2(String que2) {
		this.que2 = que2;
	}

	@Column(name = "que3", length = 45)
	public String getQue3() {
		return this.que3;
	}

	public void setQue3(String que3) {
		this.que3 = que3;
	}

	@Column(name = "que4", length = 45)
	public String getQue4() {
		return this.que4;
	}

	public void setQue4(String que4) {
		this.que4 = que4;
	}

	@Column(name = "que5", length = 45)
	public String getQue5() {
		return this.que5;
	}

	public void setQue5(String que5) {
		this.que5 = que5;
	}

	@Column(name = "comments", length = 500)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "user_name", length = 150)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_email", length = 250)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_contact", length = 150)
	public String getUserContact() {
		return this.userContact;
	}

	public void setUserContact(String userContact) {
		this.userContact = userContact;
	}

	@Column(name = "date", length = 150)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "table_no", length = 150)
	public String getTableNo() {
		return this.tableNo;
	}

	public void setTableNo(String tableNo) {
		this.tableNo = tableNo;
	}

	@Column(name = "crt_id", length = 45)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 45)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
