package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details", catalog = "starfoodlocal", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class UserDetails implements java.io.Serializable {

	private int id;
	private String fullname;
	private String email;
	private String lastname;
	private String salutation;
	private String username;
	private String password;
	private Character subscribed;
	private String mobileno;

	public UserDetails() {
	}

	public UserDetails(int id, String fullname) {
		this.id = id;
		this.fullname = fullname;
	}

	public UserDetails(int id, String fullname, String email, String lastname,
			String salutation, String username, String password,
			Character subscribed, String mobileno) {
		this.id = id;
		this.fullname = fullname;
		this.email = email;
		this.lastname = lastname;
		this.salutation = salutation;
		this.username = username;
		this.password = password;
		this.subscribed = subscribed;
		this.mobileno = mobileno;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "fullname", nullable = false, length = 100)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "lastname", length = 100)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "salutation", length = 3)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "username", unique = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "subscribed", length = 1)
	public Character getSubscribed() {
		return this.subscribed;
	}

	public void setSubscribed(Character subscribed) {
		this.subscribed = subscribed;
	}

	@Column(name = "Mobileno", length = 15)
	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

}
