package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * WeekTyp generated by hbm2java
 */
@Entity
@Table(name = "week_typ")
public class WeekTyp implements java.io.Serializable {

	private Integer id;
	private String weekTypDesc;
	@JsonIgnore
	private int weekTypF;
	@JsonIgnore
	private String crtId;
	@JsonIgnore
	private Date crtTs;
	@JsonIgnore
	private String updId;
	@JsonIgnore
	private Date updTs;
	@JsonIgnore
	private Set<CustOrdDet> orders = new HashSet<CustOrdDet>();
	@JsonIgnore
	private Set<PkgSizTyp> pkgSizTyp = new HashSet<PkgSizTyp>();
	
	public WeekTyp() {
	}

	public WeekTyp(String weekTypDesc, int weekTypF, String crtId, Date crtTs,
			String updId, Date updTs) {
		this.weekTypDesc = weekTypDesc;
		this.weekTypF = weekTypF;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "week_typ_desc", nullable = false, length = 200)
	public String getWeekTypDesc() {
		return this.weekTypDesc;
	}

	public void setWeekTypDesc(String weekTypDesc) {
		this.weekTypDesc = weekTypDesc;
	}

	@Column(name = "week_typ_f", nullable = false)
	public int getWeekTypF() {
		return this.weekTypF;
	}

	public void setWeekTypF(int weekTypF) {
		this.weekTypF = weekTypF;
	}

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", nullable = false, length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weekTyp")
	public Set<CustOrdDet> getOrders() {
		return orders;
	}

	public void setOrders(Set<CustOrdDet> orders) {
		this.orders = orders;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weekTyp")
	public Set<PkgSizTyp> getPkgSizTyp() {
		return pkgSizTyp;
	}

	public void setPkgSizTyp(Set<PkgSizTyp> pkgSizTyp) {
		this.pkgSizTyp = pkgSizTyp;
	}

}
