package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 6:26:32 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WeekDay generated by hbm2java
 */
@Entity
@Table(name = "week_day", catalog = "starfoodlocal")
public class WeekDay implements java.io.Serializable {

	private Integer id;
	private String weekDayDesc;
	private Boolean weekDayF;
	private String crtId;
	private Date crtTs;
	private String updId;
	private Date updTs;

	public WeekDay() {
	}

	public WeekDay(String weekDayDesc, String crtId, Date crtTs) {
		this.weekDayDesc = weekDayDesc;
		this.crtId = crtId;
		this.crtTs = crtTs;
	}

	public WeekDay(String weekDayDesc, Boolean weekDayF, String crtId,
			Date crtTs, String updId, Date updTs) {
		this.weekDayDesc = weekDayDesc;
		this.weekDayF = weekDayF;
		this.crtId = crtId;
		this.crtTs = crtTs;
		this.updId = updId;
		this.updTs = updTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "week_day_desc", nullable = false, length = 200)
	public String getWeekDayDesc() {
		return this.weekDayDesc;
	}

	public void setWeekDayDesc(String weekDayDesc) {
		this.weekDayDesc = weekDayDesc;
	}

	@Column(name = "week_day_f")
	public Boolean getWeekDayF() {
		return this.weekDayF;
	}

	public void setWeekDayF(Boolean weekDayF) {
		this.weekDayF = weekDayF;
	}

	@Column(name = "crt_id", nullable = false, length = 200)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Column(name = "upd_id", length = 200)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

}
