package com.nibble.starfood.hibernatemodel;

// Generated 12 Sep, 2015 3:44:29 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WtrTblRelt generated by hbm2java
 */
@Entity
@Table(name = "wtr_tbl_relt", catalog = "spiceboxcoupon")
public class WtrTblRelt implements java.io.Serializable {

	private Integer id;
	private String stfId;
	private Integer tblCode;
	private Date crtTs;
	private Date updTs;
	private String crtId;
	private String updId;
	private int ordNo;

	public WtrTblRelt() {
	}

	public WtrTblRelt(String stfId, Date crtTs, Date updTs, int ordNo) {
		this.stfId = stfId;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.ordNo = ordNo;
	}

	public WtrTblRelt(String stfId, Integer tblCode, Date crtTs, Date updTs,
			String crtId, String updId, int ordNo) {
		this.stfId = stfId;
		this.tblCode = tblCode;
		this.crtTs = crtTs;
		this.updTs = updTs;
		this.crtId = crtId;
		this.updId = updId;
		this.ordNo = ordNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "stf_id", nullable = false)
	public String getStfId() {
		return this.stfId;
	}

	public void setStfId(String stfId) {
		this.stfId = stfId;
	}

	@Column(name = "tbl_code")
	public Integer getTblCode() {
		return this.tblCode;
	}

	public void setTblCode(Integer tblCode) {
		this.tblCode = tblCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crt_ts", nullable = false, length = 19)
	public Date getCrtTs() {
		return this.crtTs;
	}

	public void setCrtTs(Date crtTs) {
		this.crtTs = crtTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_ts", nullable = false, length = 19)
	public Date getUpdTs() {
		return this.updTs;
	}

	public void setUpdTs(Date updTs) {
		this.updTs = updTs;
	}

	@Column(name = "crt_id", length = 100)
	public String getCrtId() {
		return this.crtId;
	}

	public void setCrtId(String crtId) {
		this.crtId = crtId;
	}

	@Column(name = "upd_id", length = 100)
	public String getUpdId() {
		return this.updId;
	}

	public void setUpdId(String updId) {
		this.updId = updId;
	}

	@Column(name = "ord_no", nullable = false)
	public int getOrdNo() {
		return this.ordNo;
	}

	public void setOrdNo(int ordNo) {
		this.ordNo = ordNo;
	}

}
